using ControlsLbr;
using ControlsLbr.DataGridViewExcelFilter;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Windows.Forms;

namespace RequestForRepair
{
    partial class FormJournalRequestForRepairAddEditPL
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new Container();
            DataGridViewCellStyle style = new DataGridViewCellStyle();
            DataGridViewCellStyle style2 = new DataGridViewCellStyle();
            DataGridViewCellStyle style3 = new DataGridViewCellStyle();
            DataGridViewCellStyle style4 = new DataGridViewCellStyle();
            this.dataSetN = new DataSets.DataSetN();
            this.label1 = new Label();
            this.labelRequestFiled = new Label();
            this.labelSR = new Label();
            this.cmbSR = new ComboBox();
            this.groupBox1 = new GroupBox();
            this.cmbIsPlanned = new ComboBox();
            this.labelIsPlanned = new Label();
            this.labelPurpose = new Label();
            this.txtPurpose = new TextBox();
            this.txtObject = new TextBox();
            this.cmbWorker = new ComboBox();
            this.labelObject = new Label();
            this.labelWorker = new Label();
            this.toolStripScheme = new ToolStrip();
            this.toolBtnLinkSchmObj = new ToolStripButton();
            this.toolBtnLinkSchmObjEdit = new ToolStripButton();
            this.toolBtnDelSchmObj = new ToolStripButton();
            this.toolBtnViewSChmObj = new ToolStripButton();
            this.groupBoxDaily = new GroupBox();
            this.buttonDaily = new Button();
            this.dgvDaily = new DataGridView();
            this.dataGridViewTextBoxColumn_8 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn_9 = new DataGridViewTextBoxColumn();
            this.dateBegDataGridViewTextBoxColumn = new DataGridViewFilterDateTimePickerColumn();
            this.dateEndDataGridViewTextBoxColumn = new DataGridViewFilterDateTimePickerColumn();
            this.checkBoxWeekEnd = new CheckBox();
            this.checkBoxDaily = new CheckBox();
            this.dateTimePickerEnd = new DateTimePicker();
            this.label_7 = new Label();
            this.dateTimePickerBeg = new DateTimePicker();
            this.label_3 = new Label();
            this.dtpFactEnd = new NullableDateTimePicker();
            this.label_15 = new Label();
            this.groupBoxODS = new GroupBox();
            this.cmbStatus = new ComboBox();
            this.labelStatus = new Label();
            this.txtAdress = new TextBox();
            this.cmbDispatcher = new ComboBox();
            this.label_8 = new Label();
            this.label_9 = new Label();
            this.dateTimePickerDateAgreed = new NullableDateTimePicker();
            this.checkBoxAgreed = new CheckBox();
            this.dtpDateCreate = new NullableDateTimePicker();
            this.label_14 = new Label();
            this.label_10 = new Label();
            this.label_11 = new Label();
            this.label_12 = new Label();
            this.txtComment = new TextBox();
            this.txtAgreeWith = new TextBox();
            this.buttonOK = new Button();
            this.buttonCancel = new Button();
            this.cmbUserCreate = new ComboBox();
            this.label_13 = new Label();
            this.txtNum = new TextBox();
            this.tabControl = new TabControl();
            this.tabPageGeneral = new TabPage();
            this.cmbRequestFiled = new ComboBox();
            this.toolStripMain = new ToolStrip();
            this.toolBtnCopy = new ToolStripButton();
            this.tabPageSwitching = new TabPage();
            this.dgvLinkObjects = new ControlsLbr.DataGridViewExcelFilter.DataGridViewExcelFilter();
            this.dataGridViewTextBoxColumn_0 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn_1 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn_2 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn_3 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn_4 = new DataGridViewTextBoxColumn();
            this.bindingSource_0 = new BindingSource(this.components);
            this.dataSetDoc = new DataSet();
            this.tableLinkObjects = new DataTable();
            this.dataColumn_0 = new DataColumn();
            this.dataColumn_1 = new DataColumn();
            this.dataColumn_2 = new DataColumn();
            this.dataColumn_3 = new DataColumn();
            this.dataColumn_4 = new DataColumn();
            this.dataTable_2 = new DataTable();
            this.dataColumn_5 = new DataColumn();
            this.dataColumn_6 = new DataColumn();
            this.dataColumn_7 = new DataColumn();
            this.dataColumn_8 = new DataColumn();
            this.tabPageDocuments = new TabPage();
            this.dgvDocs = new ControlsLbr.DataGridViewExcelFilter.DataGridViewExcelFilter();
            this.idDataGridViewTextBoxColumnDoc = new DataGridViewTextBoxColumn();
            this.dataGridViewImageColumnNotNull_0 = new DataGridViewImageColumnNotNull();
            this.dataGridViewTextBoxColumn_6 = new DataGridViewTextBoxColumn();
            this.dataGridViewLinkColumn_0 = new DataGridViewLinkColumn();
            this.dataGridViewTextBoxColumn_7 = new DataGridViewTextBoxColumn();
            this.bindingSource_1 = new BindingSource(this.components);
            this.toolStrip_1 = new ToolStrip();
            this.toolBtnAddDoc = new ToolStripButton();
            this.toolBtnDelDoc = new ToolStripButton();
            this.toolBtnViewDoc = new ToolStripButton();
            this.toolBtnSaveDoc = new ToolStripButton();
            this.buttonCopy = new Button();
            this.dataSetN.BeginInit();
            this.groupBox1.SuspendLayout();
            this.toolStripScheme.SuspendLayout();
            this.groupBoxDaily.SuspendLayout();
            ((ISupportInitialize)this.dgvDaily).BeginInit();
            this.groupBoxODS.SuspendLayout();
            this.tabControl.SuspendLayout();
            this.tabPageGeneral.SuspendLayout();
            this.toolStripMain.SuspendLayout();
            this.tabPageSwitching.SuspendLayout();
            ((ISupportInitialize)this.dgvLinkObjects).BeginInit();
            ((ISupportInitialize)this.bindingSource_0).BeginInit();
            this.dataSetDoc.BeginInit();
            this.tableLinkObjects.BeginInit();
            this.dataTable_2.BeginInit();
            this.tabPageDocuments.SuspendLayout();
            ((ISupportInitialize)this.dgvDocs).BeginInit();
            ((ISupportInitialize)this.bindingSource_1).BeginInit();
            this.toolStrip_1.SuspendLayout();
            base.SuspendLayout();
            this.dataSetN.DataSetName = "DataSetGES";
            this.dataSetN.SchemaSerializationMode = SchemaSerializationMode.IncludeSchema;
            this.label1.AutoSize = true;
            this.label1.Location = new Point(0x3a, 8);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x25, 13);
            this.label1.TabIndex = 0;
            this.label1.Text = "Автор";
            this.labelRequestFiled.AutoSize = true;
            this.labelRequestFiled.Location = new Point(0x13, 0x23);
            this.labelRequestFiled.Name = "labelRequestFiled";
            this.labelRequestFiled.Size = new Size(0x4c, 13);
            this.labelRequestFiled.TabIndex = 4;
            this.labelRequestFiled.Text = "Заявку подал";
            this.labelSR.AutoSize = true;
            this.labelSR.Location = new Point(0x12e, 0x23);
            this.labelSR.Name = "labelSR";
            this.labelSR.Size = new Size(0x26, 13);
            this.labelSR.TabIndex = 6;
            this.labelSR.Text = "Район";
            this.cmbSR.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
            this.cmbSR.AutoCompleteSource = AutoCompleteSource.ListItems;
            this.cmbSR.DataBindings.Add(new Binding("SelectedValue", this.dataSetN, "tJ_RequestForRepair.idSR", true));
            this.cmbSR.FormattingEnabled = true;
            this.cmbSR.Location = new Point(0x166, 0x20);
            this.cmbSR.Name = "cmbSR";
            this.cmbSR.Size = new Size(0xc6, 0x15);
            this.cmbSR.TabIndex = 7;
            this.cmbSR.SelectedIndexChanged += new System.EventHandler(this.cmbSR_SelectedIndexChanged);
            this.groupBox1.Controls.Add(this.cmbIsPlanned);
            this.groupBox1.Controls.Add(this.labelIsPlanned);
            this.groupBox1.Controls.Add(this.labelPurpose);
            this.groupBox1.Controls.Add(this.txtPurpose);
            this.groupBox1.Controls.Add(this.txtObject);
            this.groupBox1.Controls.Add(this.cmbWorker);
            this.groupBox1.Controls.Add(this.labelObject);
            this.groupBox1.Controls.Add(this.labelWorker);
            this.groupBox1.Location = new Point(11, 0x35);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(0x221, 0x61);
            this.groupBox1.TabIndex = 8;
            this.groupBox1.TabStop = false;
            this.cmbIsPlanned.FormattingEnabled = true;
            object[] items = new object[] { "Аварийный", "Плановый" };
            this.cmbIsPlanned.Items.AddRange(items);
            this.cmbIsPlanned.Location = new Point(0x65, 0x44);
            this.cmbIsPlanned.Name = "cmbIsPlanned";
            this.cmbIsPlanned.Size = new Size(0x79, 0x15);
            this.cmbIsPlanned.TabIndex = 5;
            this.cmbIsPlanned.SelectedIndexChanged += new System.EventHandler(this.cmbIsPlanned_SelectedIndexChanged);
            this.labelIsPlanned.AutoSize = true;
            this.labelIsPlanned.Location = new Point(6, 0x47);
            this.labelIsPlanned.Name = "labelIsPlanned";
            this.labelIsPlanned.Size = new Size(0x59, 13);
            this.labelIsPlanned.TabIndex = 4;
            this.labelIsPlanned.Text = "Вид отключения";
            this.labelPurpose.AutoSize = true;
            this.labelPurpose.Location = new Point(6, 0x2d);
            this.labelPurpose.Name = "labelPurpose";
            this.labelPurpose.Size = new Size(0x21, 13);
            this.labelPurpose.TabIndex = 3;
            this.labelPurpose.Text = "Цель";
            this.txtPurpose.DataBindings.Add(new Binding("Text", this.dataSetN, "tJ_RequestForRepair.Purpose", true));
            this.txtPurpose.Location = new Point(0x65, 0x2a);
            this.txtPurpose.Name = "txtPurpose";
            this.txtPurpose.Size = new Size(0x1b6, 20);
            this.txtPurpose.TabIndex = 2;
            this.txtPurpose.TextChanged += new System.EventHandler(this.txtPurpose_TextChanged);
            this.txtObject.DataBindings.Add(new Binding("Text", this.dataSetN, "tJ_RequestForRepair.schmObj", true));
            this.txtObject.Location = new Point(0x65, 0x10);
            this.txtObject.Name = "txtObject";
            this.txtObject.Size = new Size(0x1b6, 20);
            this.txtObject.TabIndex = 1;
            this.txtObject.TextChanged += new System.EventHandler(this.txtObject_TextChanged);
            this.cmbWorker.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
            this.cmbWorker.AutoCompleteSource = AutoCompleteSource.ListItems;
            this.cmbWorker.DataBindings.Add(new Binding("SelectedValue", this.dataSetN, "tJ_RequestForRepair.idWorker", true));
            this.cmbWorker.FormattingEnabled = true;
            this.cmbWorker.Location = new Point(0x13f, 0x44);
            this.cmbWorker.Name = "cmbWorker";
            this.cmbWorker.Size = new Size(0xc6, 0x15);
            this.cmbWorker.TabIndex = 3;
            this.cmbWorker.Visible = false;
            this.cmbWorker.SelectedIndexChanged += new System.EventHandler(this.cmbWorker_SelectedIndexChanged);
            this.labelObject.AutoSize = true;
            this.labelObject.Location = new Point(6, 0x10);
            this.labelObject.Name = "labelObject";
            this.labelObject.Size = new Size(0x2d, 13);
            this.labelObject.TabIndex = 0;
            this.labelObject.Text = "Объект";
            this.labelWorker.AutoSize = true;
            this.labelWorker.Location = new Point(0xfe, 0x47);
            this.labelWorker.Name = "labelWorker";
            this.labelWorker.Size = new Size(0x38, 13);
            this.labelWorker.TabIndex = 15;
            this.labelWorker.Text = "Оператор";
            this.labelWorker.Visible = false;
            this.toolStripScheme.GripStyle = ToolStripGripStyle.Hidden;
            ToolStripItem[] toolStripItems = new ToolStripItem[] { this.toolBtnLinkSchmObj, this.toolBtnLinkSchmObjEdit, this.toolBtnDelSchmObj, this.toolBtnViewSChmObj };
            this.toolStripScheme.Items.AddRange(toolStripItems);
            this.toolStripScheme.LayoutStyle = ToolStripLayoutStyle.HorizontalStackWithOverflow;
            this.toolStripScheme.Location = new Point(3, 3);
            this.toolStripScheme.Name = "toolStripScheme";
            this.toolStripScheme.Size = new Size(0x232, 0x19);
            this.toolStripScheme.TabIndex = 0x2f;
            this.toolStripScheme.Text = "toolStrip1";
            this.toolBtnLinkSchmObj.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnLinkSchmObj.Image = global::RequestForRepair.Properties.Resources.ElementAdd;
            this.toolBtnLinkSchmObj.ImageTransparentColor = Color.Magenta;
            this.toolBtnLinkSchmObj.Name = "toolBtnLinkSchmObj";
            this.toolBtnLinkSchmObj.Size = new Size(0x17, 0x16);
            this.toolBtnLinkSchmObj.Text = "Привязать к схеме";
            this.toolBtnLinkSchmObj.Click += new System.EventHandler(this.toolBtnLinkSchmObj_Click);
            this.toolBtnLinkSchmObjEdit.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnLinkSchmObjEdit.Image = global::RequestForRepair.Properties.Resources.ElementEdit;
            this.toolBtnLinkSchmObjEdit.ImageTransparentColor = Color.Magenta;
            this.toolBtnLinkSchmObjEdit.Name = "toolBtnLinkSchmObjEdit";
            this.toolBtnLinkSchmObjEdit.Size = new Size(0x17, 0x16);
            this.toolBtnLinkSchmObjEdit.Text = "Редактировать";
            this.toolBtnLinkSchmObjEdit.Click += new System.EventHandler(this.toolBtnLinkSchmObjEdit_Click);
            this.toolBtnDelSchmObj.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnDelSchmObj.Image = global::RequestForRepair.Properties.Resources.ElementDel;
            this.toolBtnDelSchmObj.ImageTransparentColor = Color.Magenta;
            this.toolBtnDelSchmObj.Name = "toolBtnDelSchmObj";
            this.toolBtnDelSchmObj.Size = new Size(0x17, 0x16);
            this.toolBtnDelSchmObj.Text = "Удалить";
            this.toolBtnDelSchmObj.Click += new System.EventHandler(this.toolBtnDelSchmObj_Click);
            this.toolBtnViewSChmObj.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnViewSChmObj.Enabled = false;
            this.toolBtnViewSChmObj.Image = global::RequestForRepair.Properties.Resources.ElementInformation;
            this.toolBtnViewSChmObj.ImageTransparentColor = Color.Magenta;
            this.toolBtnViewSChmObj.Name = "toolBtnViewSChmObj";
            this.toolBtnViewSChmObj.Size = new Size(0x17, 0x16);
            this.toolBtnViewSChmObj.Text = "Показать на схеме";
            this.toolBtnViewSChmObj.Click += new System.EventHandler(this.toolBtnViewSChmObj_Click);
            this.groupBoxDaily.Controls.Add(this.buttonDaily);
            this.groupBoxDaily.Controls.Add(this.dgvDaily);
            this.groupBoxDaily.Controls.Add(this.checkBoxWeekEnd);
            this.groupBoxDaily.Controls.Add(this.checkBoxDaily);
            this.groupBoxDaily.Controls.Add(this.dateTimePickerEnd);
            this.groupBoxDaily.Controls.Add(this.label_7);
            this.groupBoxDaily.Controls.Add(this.dateTimePickerBeg);
            this.groupBoxDaily.Controls.Add(this.label_3);
            this.groupBoxDaily.Location = new Point(11, 0x97);
            this.groupBoxDaily.Name = "groupBoxDaily";
            this.groupBoxDaily.Size = new Size(0x221, 0x8d);
            this.groupBoxDaily.TabIndex = 10;
            this.groupBoxDaily.TabStop = false;
            this.groupBoxDaily.Text = "Даты отключения";
            this.buttonDaily.Location = new Point(9, 0x73);
            this.buttonDaily.Name = "buttonDaily";
            this.buttonDaily.Size = new Size(0x4b, 0x17);
            this.buttonDaily.TabIndex = 13;
            this.buttonDaily.Text = "Добавить";
            this.buttonDaily.UseVisualStyleBackColor = true;
            this.buttonDaily.Click += new System.EventHandler(this.buttonDaily_Click);
            this.dgvDaily.AllowUserToAddRows = false;
            this.dgvDaily.AllowUserToResizeColumns = false;
            this.dgvDaily.AllowUserToResizeRows = false;
            this.dgvDaily.AutoGenerateColumns = false;
            this.dgvDaily.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            DataGridViewColumn[] dataGridViewColumns = new DataGridViewColumn[] { this.dataGridViewTextBoxColumn_8, this.dataGridViewTextBoxColumn_9, this.dateBegDataGridViewTextBoxColumn, this.dateEndDataGridViewTextBoxColumn };
            this.dgvDaily.Columns.AddRange(dataGridViewColumns);
            this.dgvDaily.DataMember = "tJ_RequestForRepairDaily";
            this.dgvDaily.DataSource = this.dataSetN;
            this.dgvDaily.Location = new Point(0xb2, 8);
            this.dgvDaily.Name = "dgvDaily";
            this.dgvDaily.RowHeadersWidth = 30;
            this.dgvDaily.Size = new Size(0x16f, 0x65);
            this.dgvDaily.TabIndex = 12;
            this.dgvDaily.VirtualMode = true;
            this.dgvDaily.CellEndEdit += new DataGridViewCellEventHandler(this.dgvDaily_CellEndEdit);
            this.dgvDaily.CellFormatting += new DataGridViewCellFormattingEventHandler(this.dgvDaily_CellFormatting);
            this.dgvDaily.EditingControlShowing += new DataGridViewEditingControlShowingEventHandler(this.dgvDaily_EditingControlShowing);
            this.dgvDaily.RowsAdded += new DataGridViewRowsAddedEventHandler(this.dgvDaily_RowsAdded);
            this.dgvDaily.RowsRemoved += new DataGridViewRowsRemovedEventHandler(this.dgvDaily_RowsRemoved);
            this.dataGridViewTextBoxColumn_8.DataPropertyName = "id";
            this.dataGridViewTextBoxColumn_8.HeaderText = "id";
            this.dataGridViewTextBoxColumn_8.Name = "idDataGridViewTextBoxColumn";
            this.dataGridViewTextBoxColumn_8.ReadOnly = true;
            this.dataGridViewTextBoxColumn_8.Visible = false;
            this.dataGridViewTextBoxColumn_9.DataPropertyName = "idRequest";
            this.dataGridViewTextBoxColumn_9.HeaderText = "idRequest";
            this.dataGridViewTextBoxColumn_9.Name = "idRequestDataGridViewTextBoxColumn";
            this.dataGridViewTextBoxColumn_9.Visible = false;
            this.dateBegDataGridViewTextBoxColumn.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.dateBegDataGridViewTextBoxColumn.DataPropertyName = "dateBeg";
            style.Format = "dd.MM.yyyy HH:mm";
            this.dateBegDataGridViewTextBoxColumn.DefaultCellStyle = style;
            this.dateBegDataGridViewTextBoxColumn.FillWeight = 50f;
            this.dateBegDataGridViewTextBoxColumn.HeaderText = "Начало";
            this.dateBegDataGridViewTextBoxColumn.Name = "dateBegDataGridViewTextBoxColumn";
            this.dateBegDataGridViewTextBoxColumn.Resizable = DataGridViewTriState.True;
            this.dateEndDataGridViewTextBoxColumn.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.dateEndDataGridViewTextBoxColumn.DataPropertyName = "dateEnd";
            style2.Format = "dd.MM.yyyy HH:mm";
            this.dateEndDataGridViewTextBoxColumn.DefaultCellStyle = style2;
            this.dateEndDataGridViewTextBoxColumn.FillWeight = 50f;
            this.dateEndDataGridViewTextBoxColumn.HeaderText = "Окончание";
            this.dateEndDataGridViewTextBoxColumn.Name = "dateEndDataGridViewTextBoxColumn";
            this.dateEndDataGridViewTextBoxColumn.Resizable = DataGridViewTriState.True;
            this.checkBoxWeekEnd.AutoSize = true;
            this.checkBoxWeekEnd.Checked = true;
            this.checkBoxWeekEnd.CheckState = CheckState.Checked;
            this.checkBoxWeekEnd.Enabled = false;
            this.checkBoxWeekEnd.Location = new Point(9, 0x5c);
            this.checkBoxWeekEnd.Name = "checkBoxWeekEnd";
            this.checkBoxWeekEnd.Size = new Size(0x4e, 0x11);
            this.checkBoxWeekEnd.TabIndex = 11;
            this.checkBoxWeekEnd.Text = "Выходные";
            this.checkBoxWeekEnd.UseVisualStyleBackColor = true;
            this.checkBoxDaily.AutoSize = true;
            this.checkBoxDaily.Location = new Point(9, 0x45);
            this.checkBoxDaily.Name = "checkBoxDaily";
            this.checkBoxDaily.Size = new Size(0x53, 0x11);
            this.checkBoxDaily.TabIndex = 10;
            this.checkBoxDaily.Text = "Ежедневно";
            this.checkBoxDaily.UseVisualStyleBackColor = true;
            this.checkBoxDaily.CheckedChanged += new System.EventHandler(this.checkBoxDaily_CheckedChanged);
            this.dateTimePickerEnd.CustomFormat = "dd.MM.yyyy HH:mm";
            this.dateTimePickerEnd.Format = DateTimePickerFormat.Custom;
            this.dateTimePickerEnd.Location = new Point(30, 0x2b);
            this.dateTimePickerEnd.Name = "dateTimePickerEnd";
            this.dateTimePickerEnd.Size = new Size(0x7c, 20);
            this.dateTimePickerEnd.TabIndex = 1;
            this.dateTimePickerEnd.ValueChanged += new System.EventHandler(this.dateTimePickerEnd_ValueChanged);
            this.label_7.AutoSize = true;
            this.label_7.Location = new Point(6, 50);
            this.label_7.Name = "label9";
            this.label_7.Size = new Size(0x13, 13);
            this.label_7.TabIndex = 9;
            this.label_7.Text = "по";
            this.dateTimePickerBeg.CustomFormat = "dd.MM.yyyy HH:mm";
            this.dateTimePickerBeg.Format = DateTimePickerFormat.Custom;
            this.dateTimePickerBeg.Location = new Point(30, 0x13);
            this.dateTimePickerBeg.Name = "dateTimePickerBeg";
            this.dateTimePickerBeg.Size = new Size(0x7c, 20);
            this.dateTimePickerBeg.TabIndex = 0;
            this.dateTimePickerBeg.ValueChanged += new System.EventHandler(this.dateTimePickerBeg_ValueChanged);
            this.label_3.AutoSize = true;
            this.label_3.Location = new Point(11, 0x16);
            this.label_3.Name = "label8";
            this.label_3.Size = new Size(13, 13);
            this.label_3.TabIndex = 8;
            this.label_3.Text = "с";
            this.dtpFactEnd.CustomFormat = ("dd.MM.yyyy HH:mm");
            this.dtpFactEnd.DataBindings.Add(new Binding("Value", this.dataSetN, "tJ_RequestForRepair.dateFactEnd", true));
            this.dtpFactEnd.Format = (DateTimePickerFormat.Custom);
            this.dtpFactEnd.Location = new Point(0x93, 0x2d);
            this.dtpFactEnd.Name = "dtpFactEnd";
            this.dtpFactEnd.Size = new Size(0xe3, 20);
            this.dtpFactEnd.TabIndex = 0x11;
            this.dtpFactEnd.Value = (new System.DateTime(0x7df, 8, 10, 13, 0x39, 6, 0x16));
            this.label_15.AutoSize = true;
            this.label_15.Location = new Point(10, 0x33);
            this.label_15.Name = "label3";
            this.label_15.Size = new Size(0x83, 13);
            this.label_15.TabIndex = 14;
            this.label_15.Text = "Время закрытия заявки";
            this.groupBoxODS.Controls.Add(this.dtpFactEnd);
            this.groupBoxODS.Controls.Add(this.label_15);
            this.groupBoxODS.Controls.Add(this.cmbStatus);
            this.groupBoxODS.Controls.Add(this.labelStatus);
            this.groupBoxODS.Controls.Add(this.txtAdress);
            this.groupBoxODS.Controls.Add(this.cmbDispatcher);
            this.groupBoxODS.Controls.Add(this.label_8);
            this.groupBoxODS.Controls.Add(this.label_9);
            this.groupBoxODS.Controls.Add(this.dateTimePickerDateAgreed);
            this.groupBoxODS.Controls.Add(this.checkBoxAgreed);
            this.groupBoxODS.Controls.Add(this.dtpDateCreate);
            this.groupBoxODS.Controls.Add(this.label_14);
            this.groupBoxODS.Controls.Add(this.label_10);
            this.groupBoxODS.Controls.Add(this.label_11);
            this.groupBoxODS.Controls.Add(this.label_12);
            this.groupBoxODS.Controls.Add(this.txtComment);
            this.groupBoxODS.Controls.Add(this.txtAgreeWith);
            this.groupBoxODS.Location = new Point(11, 0x126);
            this.groupBoxODS.Name = "groupBoxODS";
            this.groupBoxODS.Size = new Size(0x221, 0x100);
            this.groupBoxODS.TabIndex = 9;
            this.groupBoxODS.TabStop = false;
            this.groupBoxODS.VisibleChanged += new System.EventHandler(this.groupBoxODS_VisibleChanged);
            this.cmbStatus.DataBindings.Add(new Binding("SelectedValue", this.dataSetN, "tJ_RequestForRepair.status", true));
            this.cmbStatus.FormattingEnabled = true;
            this.cmbStatus.Location = new Point(0xa5, 0xe0);
            this.cmbStatus.Name = "cmbStatus";
            this.cmbStatus.Size = new Size(0x176, 0x15);
            this.cmbStatus.TabIndex = 15;
            this.labelStatus.AutoSize = true;
            this.labelStatus.Location = new Point(0x4f, 0xe3);
            this.labelStatus.Name = "labelStatus";
            this.labelStatus.Size = new Size(80, 13);
            this.labelStatus.TabIndex = 14;
            this.labelStatus.Text = "Статус заявки";
            this.txtAdress.DataBindings.Add(new Binding("Text", this.dataSetN, "tJ_RequestForRepair.Address", true));
            this.txtAdress.Location = new Point(0x6a, 0x7e);
            this.txtAdress.Multiline = true;
            this.txtAdress.Name = "txtAdress";
            this.txtAdress.Size = new Size(0x1b1, 0x40);
            this.txtAdress.TabIndex = 11;
            this.cmbDispatcher.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
            this.cmbDispatcher.AutoCompleteSource = AutoCompleteSource.ListItems;
            this.cmbDispatcher.DataBindings.Add(new Binding("SelectedValue", this.dataSetN, "tJ_RequestForRepair.WorkerAgreed", true));
            this.cmbDispatcher.FormattingEnabled = true;
            this.cmbDispatcher.Location = new Point(400, 0xc4);
            this.cmbDispatcher.Name = "cmbDispatcher";
            this.cmbDispatcher.Size = new Size(0x8b, 0x15);
            this.cmbDispatcher.TabIndex = 10;
            this.label_8.AutoSize = true;
            this.label_8.Location = new Point(0x13c, 0xc6);
            this.label_8.Name = "label14";
            this.label_8.Size = new Size(0x4e, 13);
            this.label_8.TabIndex = 9;
            this.label_8.Text = "Руководитель";
            this.label_9.AutoSize = true;
            this.label_9.Location = new Point(0x6c, 0xc6);
            this.label_9.Name = "label13";
            this.label_9.Size = new Size(0x21, 13);
            this.label_9.TabIndex = 8;
            this.label_9.Text = "Дата";
            this.dateTimePickerDateAgreed.DataBindings.Add(new Binding("Value", this.dataSetN, "tJ_RequestForRepair.DateAgreed", true));
            this.dateTimePickerDateAgreed.Location = new Point(0x93, 0xc4);
            this.dateTimePickerDateAgreed.Name = "dateTimePickerDateAgreed";
            this.dateTimePickerDateAgreed.Size = new Size(0xa3, 20);
            this.dateTimePickerDateAgreed.TabIndex = 7;
            this.dateTimePickerDateAgreed.Value = (new System.DateTime(0x7dc, 9, 0x1a, 9, 0x3a, 0x1c, 0x3a4));
            this.checkBoxAgreed.AutoSize = true;
            this.checkBoxAgreed.DataBindings.Add(new Binding("Checked", this.dataSetN, "tJ_RequestForRepair.Agreed", true));
            this.checkBoxAgreed.Location = new Point(14, 0xc7);
            this.checkBoxAgreed.Name = "checkBoxAgreed";
            this.checkBoxAgreed.Size = new Size(0x53, 0x11);
            this.checkBoxAgreed.TabIndex = 6;
            this.checkBoxAgreed.Text = "Разрешено";
            this.checkBoxAgreed.UseVisualStyleBackColor = true;
            this.checkBoxAgreed.CheckedChanged += new System.EventHandler(this.checkBoxAgreed_CheckedChanged);
            this.dtpDateCreate.CustomFormat = ("dd.MM.yyyy HH:mm");
            this.dtpDateCreate.DataBindings.Add(new Binding("Value", this.dataSetN, "tJ_RequestForRepair.dateOpenRequest", true));
            this.dtpDateCreate.Format = (DateTimePickerFormat.Custom);
            this.dtpDateCreate.Location = new Point(0x93, 0x13);
            this.dtpDateCreate.Name = "dtpDateCreate";
            this.dtpDateCreate.Size = new Size(0xe3, 20);
            this.dtpDateCreate.TabIndex = 0x11;
            this.dtpDateCreate.Value = (new System.DateTime(0x7dc, 10, 0x12, 8, 0x27, 0x29, 0xb2));
            this.label_14.AutoSize = true;
            this.label_14.Location = new Point(11, 0x15);
            this.label_14.Name = "label2";
            this.label_14.Size = new Size(130, 13);
            this.label_14.TabIndex = 0x10;
            this.label_14.Text = "Время открытия заявки";
            this.label_10.AutoSize = true;
            this.label_10.Location = new Point(11, 0x81);
            this.label_10.Name = "label12";
            this.label_10.Size = new Size(0x2c, 13);
            this.label_10.TabIndex = 5;
            this.label_10.Text = "Адреса";
            this.label_11.AutoSize = true;
            this.label_11.Location = new Point(11, 0x67);
            this.label_11.Name = "label11";
            this.label_11.Size = new Size(0x4d, 13);
            this.label_11.TabIndex = 4;
            this.label_11.Text = "Комментарий";
            this.label_12.AutoSize = true;
            this.label_12.Location = new Point(11, 0x4d);
            this.label_12.Name = "label10";
            this.label_12.Size = new Size(0x51, 13);
            this.label_12.TabIndex = 3;
            this.label_12.Text = "Согласовать с";
            this.txtComment.DataBindings.Add(new Binding("Text", this.dataSetN, "tJ_RequestForRepair.Comment", true));
            this.txtComment.Location = new Point(0x6a, 100);
            this.txtComment.Name = "txtComment";
            this.txtComment.Size = new Size(0x1b1, 20);
            this.txtComment.TabIndex = 1;
            this.txtAgreeWith.DataBindings.Add(new Binding("Text", this.dataSetN, "tJ_RequestForRepair.AgreeWith", true));
            this.txtAgreeWith.Location = new Point(0x6a, 0x4a);
            this.txtAgreeWith.Name = "txtAgreeWith";
            this.txtAgreeWith.Size = new Size(0x1b1, 20);
            this.txtAgreeWith.TabIndex = 0;
            this.buttonOK.DialogResult = DialogResult.OK;
            this.buttonOK.Location = new Point(15, 0x24b);
            this.buttonOK.Name = "buttonOK";
            this.buttonOK.Size = new Size(0x4b, 0x17);
            this.buttonOK.TabIndex = 10;
            this.buttonOK.Text = "ОК";
            this.buttonOK.UseVisualStyleBackColor = true;
            this.buttonOK.Click += new System.EventHandler(this.buttonOK_Click);
            this.buttonCancel.DialogResult = DialogResult.Cancel;
            this.buttonCancel.Location = new Point(0x1e5, 0x24b);
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.Size = new Size(0x4b, 0x17);
            this.buttonCancel.TabIndex = 11;
            this.buttonCancel.Text = "Отмена";
            this.buttonCancel.UseVisualStyleBackColor = true;
            this.buttonCancel.Click += new System.EventHandler(this.buttonCancel_Click);
            this.cmbUserCreate.DataBindings.Add(new Binding("SelectedValue", this.dataSetN, "tJ_RequestForRepair.idUserCreate", true));
            this.cmbUserCreate.Enabled = false;
            this.cmbUserCreate.FormattingEnabled = true;
            this.cmbUserCreate.Location = new Point(0x65, 5);
            this.cmbUserCreate.Name = "cmbUserCreate";
            this.cmbUserCreate.Size = new Size(0xb5, 0x15);
            this.cmbUserCreate.TabIndex = 12;
            this.label_13.AutoSize = true;
            this.label_13.Location = new Point(0x12e, 8);
            this.label_13.Name = "label15";
            this.label_13.Size = new Size(0x29, 13);
            this.label_13.TabIndex = 13;
            this.label_13.Text = "Номер";
            this.txtNum.DataBindings.Add(new Binding("Text", this.dataSetN, "tJ_RequestForRepair.num", true));
            this.txtNum.Location = new Point(0x166, 5);
            this.txtNum.Name = "txtNum";
            this.txtNum.ReadOnly = true;
            this.txtNum.Size = new Size(0xc6, 20);
            this.txtNum.TabIndex = 14;
            this.tabControl.Controls.Add(this.tabPageGeneral);
            this.tabControl.Controls.Add(this.tabPageSwitching);
            this.tabControl.Controls.Add(this.tabPageDocuments);
            this.tabControl.Location = new Point(0, 0);
            this.tabControl.Name = "tabControl";
            this.tabControl.SelectedIndex = 0;
            this.tabControl.Size = new Size(0x240, 0x245);
            this.tabControl.TabIndex = 0x31;
            this.tabPageGeneral.Controls.Add(this.cmbRequestFiled);
            this.tabPageGeneral.Controls.Add(this.toolStripMain);
            this.tabPageGeneral.Controls.Add(this.cmbSR);
            this.tabPageGeneral.Controls.Add(this.label1);
            this.tabPageGeneral.Controls.Add(this.groupBoxDaily);
            this.tabPageGeneral.Controls.Add(this.labelRequestFiled);
            this.tabPageGeneral.Controls.Add(this.groupBoxODS);
            this.tabPageGeneral.Controls.Add(this.groupBox1);
            this.tabPageGeneral.Controls.Add(this.labelSR);
            this.tabPageGeneral.Controls.Add(this.cmbUserCreate);
            this.tabPageGeneral.Controls.Add(this.txtNum);
            this.tabPageGeneral.Controls.Add(this.label_13);
            this.tabPageGeneral.Location = new Point(4, 0x16);
            this.tabPageGeneral.Name = "tabPageGeneral";
            this.tabPageGeneral.Padding = new Padding(3);
            this.tabPageGeneral.Size = new Size(0x238, 0x22b);
            this.tabPageGeneral.TabIndex = 0;
            this.tabPageGeneral.Text = "Общие";
            this.tabPageGeneral.UseVisualStyleBackColor = true;
            this.cmbRequestFiled.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
            this.cmbRequestFiled.AutoCompleteSource = AutoCompleteSource.ListItems;
            this.cmbRequestFiled.DataBindings.Add(new Binding("Text", this.dataSetN, "tJ_RequestForRepair.reguestFiled", true));
            this.cmbRequestFiled.FormattingEnabled = true;
            this.cmbRequestFiled.Location = new Point(0x65, 0x20);
            this.cmbRequestFiled.Name = "cmbRequestFiled";
            this.cmbRequestFiled.Size = new Size(0xb5, 0x15);
            this.cmbRequestFiled.TabIndex = 0x13;
            this.toolStripMain.Dock = DockStyle.None;
            this.toolStripMain.GripStyle = ToolStripGripStyle.Hidden;
            ToolStripItem[] itemArray2 = new ToolStripItem[] { this.toolBtnCopy };
            this.toolStripMain.Items.AddRange(itemArray2);
            this.toolStripMain.Location = new Point(0, 0);
            this.toolStripMain.Name = "toolStripMain";
            this.toolStripMain.Size = new Size(0x1a, 0x19);
            this.toolStripMain.TabIndex = 0x12;
            this.toolStripMain.Text = "toolStrip1";
            this.toolBtnCopy.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnCopy.Image = global::RequestForRepair.Properties.Resources.CopyBuffer;
            this.toolBtnCopy.ImageTransparentColor = Color.Magenta;
            this.toolBtnCopy.Name = "toolBtnCopy";
            this.toolBtnCopy.Size = new Size(0x17, 0x16);
            this.toolBtnCopy.Text = "Копировать";
            this.toolBtnCopy.Click += new System.EventHandler(this.toolBtnCopy_Click);
            this.tabPageSwitching.Controls.Add(this.dgvLinkObjects);
            this.tabPageSwitching.Controls.Add(this.toolStripScheme);
            this.tabPageSwitching.Location = new Point(4, 0x16);
            this.tabPageSwitching.Name = "tabPageSwitching";
            this.tabPageSwitching.Padding = new Padding(3);
            this.tabPageSwitching.Size = new Size(0x238, 0x22b);
            this.tabPageSwitching.TabIndex = 1;
            this.tabPageSwitching.Text = "Оперативные переключения";
            this.tabPageSwitching.UseVisualStyleBackColor = true;
            this.dgvLinkObjects.AllowUserToAddRows = false;
            this.dgvLinkObjects.AllowUserToDeleteRows = false;
            this.dgvLinkObjects.AllowUserToOrderColumns = true;
            this.dgvLinkObjects.AllowUserToVisibleColumns = (false);
            this.dgvLinkObjects.AutoGenerateColumns = false;
            this.dgvLinkObjects.AutoSizeRowsMode = DataGridViewAutoSizeRowsMode.AllCells;
            this.dgvLinkObjects.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            DataGridViewColumn[] columnArray2 = new DataGridViewColumn[]
            {
                this.dataGridViewTextBoxColumn_0,
                this.dataGridViewTextBoxColumn_1,
                this.dataGridViewTextBoxColumn_2,
                this.dataGridViewTextBoxColumn_3,
                this.dataGridViewTextBoxColumn_4
            };
            this.dgvLinkObjects.Columns.AddRange(columnArray2);
            this.dgvLinkObjects.DataSource = this.bindingSource_0;
            this.dgvLinkObjects.Dock = DockStyle.Fill;
            this.dgvLinkObjects.Location = new Point(3, 0x1c);
            this.dgvLinkObjects.Name = "dgvLinkObjects";
            this.dgvLinkObjects.ReadOnly = true;
            this.dgvLinkObjects.RowHeadersWidth = 0x15;
            this.dgvLinkObjects.RowHeadersWidthSizeMode = DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            this.dgvLinkObjects.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvLinkObjects.Size = new Size(0x232, 0x20c);
            this.dgvLinkObjects.TabIndex = 0x31;
            this.dgvLinkObjects.CellDoubleClick += new DataGridViewCellEventHandler(this.dgvLinkObjects_CellDoubleClick);
            this.dataGridViewTextBoxColumn_0.DataPropertyName = "Objects";
            style3.WrapMode = DataGridViewTriState.True;
            this.dataGridViewTextBoxColumn_0.DefaultCellStyle = style3;
            this.dataGridViewTextBoxColumn_0.HeaderText = "Объекты";
            this.dataGridViewTextBoxColumn_0.Name = "objectsDataGridViewTextBoxColumn1";
            this.dataGridViewTextBoxColumn_0.ReadOnly = true;
            this.dataGridViewTextBoxColumn_0.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.dataGridViewTextBoxColumn_0.Width = 250;
            this.dataGridViewTextBoxColumn_1.DataPropertyName = "DateBeg";
            this.dataGridViewTextBoxColumn_1.HeaderText = "Начало";
            this.dataGridViewTextBoxColumn_1.Name = "dateBegDataGridViewTextBoxColumn2";
            this.dataGridViewTextBoxColumn_1.ReadOnly = true;
            this.dataGridViewTextBoxColumn_1.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.dataGridViewTextBoxColumn_1.Width = 90;
            this.dataGridViewTextBoxColumn_2.DataPropertyName = "DateEnd";
            this.dataGridViewTextBoxColumn_2.HeaderText = "Окончание";
            this.dataGridViewTextBoxColumn_2.Name = "dateEndDataGridViewTextBoxColumn2";
            this.dataGridViewTextBoxColumn_2.ReadOnly = true;
            this.dataGridViewTextBoxColumn_2.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.dataGridViewTextBoxColumn_2.Width = 90;
            this.dataGridViewTextBoxColumn_3.DataPropertyName = "Duration";
            this.dataGridViewTextBoxColumn_3.HeaderText = "Длительность";
            this.dataGridViewTextBoxColumn_3.Name = "durationDataGridViewTextBoxColumn1";
            this.dataGridViewTextBoxColumn_3.ReadOnly = true;
            this.dataGridViewTextBoxColumn_3.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.dataGridViewTextBoxColumn_3.Width = 90;
            this.dataGridViewTextBoxColumn_4.DataPropertyName = "Num";
            this.dataGridViewTextBoxColumn_4.HeaderText = "Num";
            this.dataGridViewTextBoxColumn_4.Name = "numDataGridViewTextBoxColumn1";
            this.dataGridViewTextBoxColumn_4.ReadOnly = true;
            this.dataGridViewTextBoxColumn_4.Visible = false;
            this.bindingSource_0.DataMember = "tableLinkObjects";
            this.bindingSource_0.DataSource = this.dataSetDoc;
            this.bindingSource_0.Sort = "Num";
            this.dataSetDoc.DataSetName = "NewDataSet";
            DataTable[] tables = new DataTable[] { this.tableLinkObjects, this.dataTable_2 };
            this.dataSetDoc.Tables.AddRange(tables);
            DataColumn[] columns = new DataColumn[] { this.dataColumn_0, this.dataColumn_1, this.dataColumn_2, this.dataColumn_3, this.dataColumn_4 };
            this.tableLinkObjects.Columns.AddRange(columns);
            this.tableLinkObjects.TableName = "tableLinkObjects";
            this.dataColumn_0.ColumnName = "Objects";
            this.dataColumn_1.ColumnName = "DateBeg";
            this.dataColumn_1.DataType = typeof(System.DateTime);
            this.dataColumn_2.ColumnName = "DateEnd";
            this.dataColumn_2.DataType = typeof(System.DateTime);
            this.dataColumn_3.ColumnName = "Duration";
            this.dataColumn_4.ColumnName = "Num";
            this.dataColumn_4.DataType = typeof(short);
            DataColumn[] columnArray4 = new DataColumn[] { this.dataColumn_5, this.dataColumn_6, this.dataColumn_7, this.dataColumn_8 };
            this.dataTable_2.Columns.AddRange(columnArray4);
            Constraint[] constraints = new Constraint[1];
            string[] columnNames = new string[] { "id" };
            constraints[0] = new UniqueConstraint("Constraint1", columnNames, true);
            this.dataTable_2.Constraints.AddRange(constraints);
            this.dataTable_2.PrimaryKey = new DataColumn[] { this.dataColumn_5 };
            this.dataTable_2.TableName = "tJ_RequestForReapirDoc";
            this.dataColumn_5.AllowDBNull = false;
            this.dataColumn_5.AutoIncrement = true;
            this.dataColumn_5.ColumnName = "id";
            this.dataColumn_5.DataType = typeof(int);
            this.dataColumn_6.AllowDBNull = false;
            this.dataColumn_6.ColumnName = "idRequest";
            this.dataColumn_6.DataType = typeof(int);
            this.dataColumn_7.ColumnName = "FileName";
            this.dataColumn_8.ColumnName = "Comment";
            this.tabPageDocuments.Controls.Add(this.dgvDocs);
            this.tabPageDocuments.Controls.Add(this.toolStrip_1);
            this.tabPageDocuments.Location = new Point(4, 0x16);
            this.tabPageDocuments.Name = "tabPageDocuments";
            this.tabPageDocuments.Padding = new Padding(3);
            this.tabPageDocuments.Size = new Size(0x238, 0x22b);
            this.tabPageDocuments.TabIndex = 2;
            this.tabPageDocuments.Text = "Документы";
            this.tabPageDocuments.UseVisualStyleBackColor = true;
            this.dgvDocs.AllowUserToAddRows = false;
            this.dgvDocs.AllowUserToDeleteRows = false;
            this.dgvDocs.AutoGenerateColumns = false;
            this.dgvDocs.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            DataGridViewColumn[] columnArray6 = new DataGridViewColumn[]
            {
                this.idDataGridViewTextBoxColumnDoc,
                this.dataGridViewImageColumnNotNull_0,
                this.dataGridViewTextBoxColumn_6,
                this.dataGridViewLinkColumn_0,
                this.dataGridViewTextBoxColumn_7
            };
            this.dgvDocs.Columns.AddRange(columnArray6);
            this.dgvDocs.DataSource = this.bindingSource_1;
            this.dgvDocs.Dock = DockStyle.Fill;
            this.dgvDocs.Location = new Point(3, 0x1c);
            this.dgvDocs.Name = "dgvDocs";
            this.dgvDocs.RowHeadersWidth = 0x15;
            this.dgvDocs.Size = new Size(0x232, 0x20c);
            this.dgvDocs.TabIndex = 1;
            this.dgvDocs.VirtualMode = true;
            this.dgvDocs.CellContentClick += new DataGridViewCellEventHandler(this.dgvDocs_CellContentClick);
            this.dgvDocs.CellValueNeeded += new DataGridViewCellValueEventHandler(this.dgvDocs_CellValueNeeded);
            this.idDataGridViewTextBoxColumnDoc.DataPropertyName = "id";
            this.idDataGridViewTextBoxColumnDoc.HeaderText = "id";
            this.idDataGridViewTextBoxColumnDoc.Name = "idDataGridViewTextBoxColumnDoc";
            this.idDataGridViewTextBoxColumnDoc.ReadOnly = true;
            this.idDataGridViewTextBoxColumnDoc.Visible = false;
            style4.NullValue = null;
            this.dataGridViewImageColumnNotNull_0.DefaultCellStyle = style4;
            this.dataGridViewImageColumnNotNull_0.HeaderText = "";
            this.dataGridViewImageColumnNotNull_0.Name = "ColumnImage";
            this.dataGridViewImageColumnNotNull_0.ReadOnly = true;
            this.dataGridViewImageColumnNotNull_0.Resizable = DataGridViewTriState.False;
            this.dataGridViewImageColumnNotNull_0.Width = 30;
            this.dataGridViewTextBoxColumn_6.DataPropertyName = "idRequest";
            this.dataGridViewTextBoxColumn_6.HeaderText = "idRequest";
            this.dataGridViewTextBoxColumn_6.Name = "idRequestDataGridViewTextBoxColumn1";
            this.dataGridViewTextBoxColumn_6.Visible = false;
            this.dataGridViewLinkColumn_0.DataPropertyName = "FileName";
            this.dataGridViewLinkColumn_0.HeaderText = "Файл";
            this.dataGridViewLinkColumn_0.Name = "fileNameDataGridViewTextBoxColumn";
            this.dataGridViewLinkColumn_0.ReadOnly = true;
            this.dataGridViewLinkColumn_0.Resizable = DataGridViewTriState.True;
            this.dataGridViewLinkColumn_0.SortMode = DataGridViewColumnSortMode.Automatic;
            this.dataGridViewLinkColumn_0.Width = 200;
            this.dataGridViewTextBoxColumn_7.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.dataGridViewTextBoxColumn_7.DataPropertyName = "Comment";
            this.dataGridViewTextBoxColumn_7.HeaderText = "Комментарий";
            this.dataGridViewTextBoxColumn_7.Name = "commentDataGridViewTextBoxColumn";
            this.bindingSource_1.DataMember = "tJ_RequestForRepairDoc";
            this.bindingSource_1.DataSource = this.dataSetN;
            ToolStripItem[] itemArray3 = new ToolStripItem[] { this.toolBtnAddDoc, this.toolBtnDelDoc, this.toolBtnViewDoc, this.toolBtnSaveDoc };
            this.toolStrip_1.Items.AddRange(itemArray3);
            this.toolStrip_1.Location = new Point(3, 3);
            this.toolStrip_1.Name = "toolStripDocuments";
            this.toolStrip_1.Size = new Size(0x232, 0x19);
            this.toolStrip_1.TabIndex = 0;
            this.toolStrip_1.Text = "toolStrip1";
            this.toolBtnAddDoc.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnAddDoc.Image = global::RequestForRepair.Properties.Resources.ElementAdd;
            this.toolBtnAddDoc.ImageTransparentColor = Color.Magenta;
            this.toolBtnAddDoc.Name = "toolBtnAddDoc";
            this.toolBtnAddDoc.Size = new Size(0x17, 0x16);
            this.toolBtnAddDoc.Text = "Добавить документ";
            this.toolBtnAddDoc.Click += new System.EventHandler(this.toolBtnAddDoc_Click);
            this.toolBtnDelDoc.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnDelDoc.Image = global::RequestForRepair.Properties.Resources.ElementDel;
            this.toolBtnDelDoc.ImageTransparentColor = Color.Magenta;
            this.toolBtnDelDoc.Name = "toolBtnDelDoc";
            this.toolBtnDelDoc.Size = new Size(0x17, 0x16);
            this.toolBtnDelDoc.Text = "Удалить документ";
            this.toolBtnDelDoc.Click += new System.EventHandler(this.toolBtnDelDoc_Click);
            this.toolBtnViewDoc.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnViewDoc.Image = global::RequestForRepair.Properties.Resources.ElementInformation;
            this.toolBtnViewDoc.ImageTransparentColor = Color.Magenta;
            this.toolBtnViewDoc.Name = "toolBtnViewDoc";
            this.toolBtnViewDoc.Size = new Size(0x17, 0x16);
            this.toolBtnViewDoc.Text = "Открыть документ";
            this.toolBtnViewDoc.Click += new System.EventHandler(this.toolBtnViewDoc_Click);
            this.toolBtnSaveDoc.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnSaveDoc.Image = global::RequestForRepair.Properties.Resources.ElementGo;
            this.toolBtnSaveDoc.ImageTransparentColor = Color.Magenta;
            this.toolBtnSaveDoc.Name = "toolBtnSaveDoc";
            this.toolBtnSaveDoc.Size = new Size(0x17, 0x16);
            this.toolBtnSaveDoc.Text = "Сохранить документ";
            this.toolBtnSaveDoc.Click += new System.EventHandler(this.toolBtnSaveDoc_Click);
            this.buttonCopy.Location = new Point(240, 0x24b);
            this.buttonCopy.Name = "buttonCopy";
            this.buttonCopy.Size = new Size(0x4b, 0x17);
            this.buttonCopy.TabIndex = 50;
            this.buttonCopy.Text = "Копировать";
            this.buttonCopy.UseVisualStyleBackColor = true;
            this.buttonCopy.Visible = false;
            this.buttonCopy.Click += new System.EventHandler(this.toolBtnCopy_Click);
            base.AcceptButton = this.buttonOK;
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.CancelButton = this.buttonCancel;
            base.ClientSize = new Size(0x23c, 0x26b);
            base.Controls.Add(this.buttonCopy);
            base.Controls.Add(this.tabControl);
            base.Controls.Add(this.buttonCancel);
            base.Controls.Add(this.buttonOK);
            base.FormBorderStyle = FormBorderStyle.FixedDialog;
            base.MaximizeBox = false;
            base.Name = "FormJournalRequestForRepairAddEdit";
            this.Text = "FormJournalRequestForRepairAddEdit";
            base.FormClosing += new FormClosingEventHandler(this.FormJournalRequestForRepairAddEdit_FormClosing);
            base.FormClosed += new FormClosedEventHandler(this.FormJournalRequestForRepairAddEdit_FormClosed);
            base.Load += new System.EventHandler(this.FormJournalRequestForRepairAddEdit_Load);
            this.dataSetN.EndInit();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.toolStripScheme.ResumeLayout(false);
            this.toolStripScheme.PerformLayout();
            this.groupBoxDaily.ResumeLayout(false);
            this.groupBoxDaily.PerformLayout();
            ((ISupportInitialize)this.dgvDaily).EndInit();
            this.groupBoxODS.ResumeLayout(false);
            this.groupBoxODS.PerformLayout();
            this.tabControl.ResumeLayout(false);
            this.tabPageGeneral.ResumeLayout(false);
            this.tabPageGeneral.PerformLayout();
            this.toolStripMain.ResumeLayout(false);
            this.toolStripMain.PerformLayout();
            this.tabPageSwitching.ResumeLayout(false);
            this.tabPageSwitching.PerformLayout();
            ((ISupportInitialize)this.dgvLinkObjects).EndInit();
            ((ISupportInitialize)this.bindingSource_0).EndInit();
            this.dataSetDoc.EndInit();
            this.tableLinkObjects.EndInit();
            this.dataTable_2.EndInit();
            this.tabPageDocuments.ResumeLayout(false);
            this.tabPageDocuments.PerformLayout();
            ((ISupportInitialize)this.dgvDocs).EndInit();
            ((ISupportInitialize)this.bindingSource_1).EndInit();
            this.toolStrip_1.ResumeLayout(false);
            this.toolStrip_1.PerformLayout();
            base.ResumeLayout(false);
        }

        private BindingSource bindingSource_0;
        private BindingSource bindingSource_1;

        private Button buttonOK;
        private Button buttonCancel;
        private Button buttonDaily;
        private Button buttonCopy;
        private CheckBox checkBoxAgreed;
        private CheckBox checkBoxWeekEnd;
        private CheckBox checkBoxDaily;
        private ComboBox cmbSR;
        private ComboBox cmbIsPlanned;
        private ComboBox cmbDispatcher;
        private ComboBox cmbUserCreate;
        private ComboBox cmbRequestFiled;
        private ComboBox cmbStatus;
        private ComboBox cmbWorker;
        private DataColumn dataColumn_0;
        private DataColumn dataColumn_1;
        private DataColumn dataColumn_2;
        private DataColumn dataColumn_3;
        private DataColumn dataColumn_4;
        private DataColumn dataColumn_5;
        private DataColumn dataColumn_6;
        private DataColumn dataColumn_7;
        private DataColumn dataColumn_8;
        private DataGridView dgvDaily;
        private ControlsLbr.DataGridViewExcelFilter.DataGridViewExcelFilter dgvLinkObjects;
        private ControlsLbr.DataGridViewExcelFilter.DataGridViewExcelFilter dgvDocs;
        private ControlsLbr.DataGridViewExcelFilter.DataGridViewFilterDateTimePickerColumn dateBegDataGridViewTextBoxColumn;
        private ControlsLbr.DataGridViewExcelFilter.DataGridViewFilterDateTimePickerColumn dateEndDataGridViewTextBoxColumn;
        private ControlsLbr.DataGridViewExcelFilter.DataGridViewImageColumnNotNull dataGridViewImageColumnNotNull_0;
        private DataGridViewLinkColumn dataGridViewLinkColumn_0;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn_0;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn_1;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn_2;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn_3;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn_4;
        private DataGridViewTextBoxColumn idDataGridViewTextBoxColumnDoc;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn_6;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn_7;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn_8;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn_9;

        private DataSet dataSetDoc;
        private DataSets.DataSetN dataSetN;
        private DataTable dataTable_0;
        private DataTable tableLinkObjects;
        private DataTable dataTable_2;

        private DateTimePicker dateTimePickerEnd;
        private DateTimePicker dateTimePickerBeg;


        private GroupBox groupBox1;
        private GroupBox groupBoxODS;
        private GroupBox groupBoxDaily;


        private Label label1;
        private Label labelRequestFiled;
        private Label label_10;
        private Label label_11;
        private Label label_12;
        private Label label_13;
        private Label label_14;
        private Label label_15;
        private Label labelStatus;
        private Label labelWorker;
        private Label labelSR;
        private Label label_3;
        private Label labelIsPlanned;
        private Label labelPurpose;
        private Label labelObject;
        private Label label_7;
        private Label label_8;
        private Label label_9;
        private NullableDateTimePicker dateTimePickerDateAgreed;
        private NullableDateTimePicker dtpDateCreate;
        private NullableDateTimePicker dtpFactEnd;
        private TabControl tabControl;
        private TabPage tabPageGeneral;
        private TabPage tabPageSwitching;
        private TabPage tabPageDocuments;
        private TextBox txtPurpose;
        private TextBox txtObject;
        private TextBox txtComment;
        private TextBox txtAgreeWith;
        private TextBox txtNum;
        private TextBox txtAdress;
        private ToolStrip toolStripScheme;
        private ToolStrip toolStrip_1;
        private ToolStrip toolStripMain;
        private ToolStripButton toolBtnLinkSchmObj;
        private ToolStripButton toolBtnDelSchmObj;
        private ToolStripButton toolBtnViewSChmObj;
        private ToolStripButton toolBtnLinkSchmObjEdit;
        private ToolStripButton toolBtnAddDoc;
        private ToolStripButton toolBtnDelDoc;
        private ToolStripButton toolBtnViewDoc;
        private ToolStripButton toolBtnSaveDoc;
        private ToolStripButton toolBtnCopy;
    }
}
