using ControlsLbr;
using System;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Windows.Forms;

namespace JournalOrder
{
    internal partial class FormJournalOrderAddEdit
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private System.ComponentModel.IContainer components = null;

        private void InitializeComponent()
        {
            DataGridViewCellStyle dataGridViewCellStyle = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle3 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle4 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle5 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle6 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle7 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle8 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle9 = new DataGridViewCellStyle();
            this.label1 = new Label();
            this.txtNumOrder = new TextBox();
            this.dataSetOrder = new DataSet.DataSetOrder();
            this.labelDateBegin = new Label();
            this.labelDateEnd = new Label();
            this.labelInstruction = new Label();
            this.richTxtInstruction = new RichTextBox();
            this.labelSR = new Label();
            this.cmbSR = new ComboBox();
            this.label6 = new Label();
            this.labelAccept = new Label();
            this.label8 = new Label();
            this.labelMaker = new Label();
            this.label10 = new Label();
            this.label11 = new Label();
            this.richTxtOtrherInstructions = new RichTextBox();
            this.labelOutput = new Label();
            this.cmbAcceptWorker = new ComboBox();
            this.dateTimePickerDateBegin = new NullableDateTimePicker();
            this.dateTimePickerDateEnd = new NullableDateTimePicker();
            this.cmbHeadWorker = new ComboBox();
            this.cmbWatchWorker = new ComboBox();
            this.cmbMakerWorker = new ComboBox();
            this.cmbOutputWorker = new ComboBox();
            this.dateTimePickerDateOutput = new NullableDateTimePicker();
            this.buttonSave = new Button();
            this.buttonRegister = new Button();
            this.dgvBrigade = new DataGridView();
            this.idDataGridViewTextBoxColumn = new DataGridViewTextBoxColumn();
            this.idOrderDataGridViewTextBoxColumn = new DataGridViewTextBoxColumn();
            this.brigadeWorkerColumn = new DataGridViewComboBoxColumn();
            this.GroupElectricalTxtColumn = new DataGridViewTextBoxColumn();
            this.idJobTitleDgvColumn = new DataGridViewComboBoxColumn();
            this.isUnderstudyDgvColumn = new DataGridViewCheckBoxColumn();
            this.label13 = new Label();
            this.dgvInstruction = new DataGridView();
            this.idDataGridViewTextBoxColumn1 = new DataGridViewTextBoxColumn();
            this.idOrderDgvColumnInstruction = new DataGridViewTextBoxColumn();
            this.nameObjDataGridViewTextBoxColumn = new DataGridViewTextBoxColumn();
            this.instructionDataGridViewTextBoxColumn = new DataGridViewTextBoxColumn();
            this.recnumDataGridViewTextBoxColumn = new DataGridViewTextBoxColumn();
            this.dgvResolution = new DataGridView();
            this.idDataGridViewTextBoxColumn2 = new DataGridViewTextBoxColumn();
            this.idOrderDataGridViewTextBoxColumn1 = new DataGridViewTextBoxColumn();
            this.workerResolutionColumn = new DataGridViewComboBoxColumn();
            this.dateBeginDataGridViewTextBoxColumn = new DataGridViewTextBoxColumn();
            this.dateEndDataGridViewTextBoxColumn = new DataGridViewTextBoxColumn();
            this.cmbWorkerResolution = new ComboBox();
            this.dateTimePickerResolution = new NullableDateTimePicker();
            this.buttonResolution = new Button();
            this.buttonCloseOrder = new Button();
            this.dateTimePickerClose = new NullableDateTimePicker();
            this.cmbCloseWorker = new ComboBox();
            this.toolStripReport = new ToolStrip();
            this.toolBtnReport = new ToolStripButton();
            this.toolBtnCopyOrder = new ToolStripButton();
            this.splitContainer = new SplitContainer();
            this.labelOutputDate = new Label();
            this.panelExtension = new Panel();
            this.buttonExtension = new Button();
            this.dateTimePickerDateEndExt = new NullableDateTimePicker();
            this.cmbExtWorker = new MultiColumnComboBox();
            this.label3 = new Label();
            this.txtOutputWorker = new TextBox();
            this.toolStripScheme = new ToolStrip();
            this.toolBtnLinkSchmObj = new ToolStripButton();
            this.toolBtnDelSchmObj = new ToolStripButton();
            this.toolBtnViewSChmObj = new ToolStripButton();
            this.listBoxLinkScmObjects = new ListBox();
            this.labelDivision = new Label();
            this.cmbDivision = new ComboBoxReadOnly();
            this.label4 = new Label();
            this.txtMakerWorker = new TextBox();
            this.txtWatchWorker = new TextBox();
            this.txtAcceptWorker = new TextBox();
            this.txtHeadWorker = new TextBox();
            this.label2 = new Label();
            ((ISupportInitialize)this.dataSetOrder).BeginInit();
            ((ISupportInitialize)this.dgvBrigade).BeginInit();
            ((ISupportInitialize)this.dgvInstruction).BeginInit();
            ((ISupportInitialize)this.dgvResolution).BeginInit();
            this.toolStripReport.SuspendLayout();
            this.splitContainer.Panel1.SuspendLayout();
            this.splitContainer.Panel2.SuspendLayout();
            this.splitContainer.SuspendLayout();
            this.panelExtension.SuspendLayout();
            this.toolStripScheme.SuspendLayout();
            base.SuspendLayout();
            this.label1.AutoSize = true;
            this.label1.Location = new Point(13, 37);
            this.label1.Name = "label1";
            this.label1.Size = new Size(91, 13);
            this.label1.TabIndex = 0;
            this.label1.Text = "Наряд-допуск №";
            this.txtNumOrder.Anchor = (AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right);
            this.txtNumOrder.DataBindings.Add(new Binding("Text", this.dataSetOrder, "tJ_Order.num", true));
            this.txtNumOrder.Location = new Point(110, 34);
            this.txtNumOrder.Name = "txtNumOrder";
            this.txtNumOrder.ReadOnly = true;
            this.txtNumOrder.Size = new Size(102, 20);
            this.txtNumOrder.TabIndex = 1;
            this.dataSetOrder.DataSetName = "DataSetOrder";
            this.dataSetOrder.SchemaSerializationMode = SchemaSerializationMode.IncludeSchema;
            this.labelDateBegin.AutoSize = true;
            this.labelDateBegin.Location = new Point(13, 77);
            this.labelDateBegin.Name = "labelDateBegin";
            this.labelDateBegin.Size = new Size(84, 13);
            this.labelDateBegin.TabIndex = 2;
            this.labelDateBegin.Text = "Начало работы";
            this.labelDateEnd.AutoSize = true;
            this.labelDateEnd.Location = new Point(13, 99);
            this.labelDateEnd.Name = "labelDateEnd";
            this.labelDateEnd.Size = new Size(102, 13);
            this.labelDateEnd.TabIndex = 3;
            this.labelDateEnd.Text = "Окончание работы";
            this.labelInstruction.AutoSize = true;
            this.labelInstruction.Font = new Font("Microsoft Sans Serif", 10f, FontStyle.Regular, GraphicsUnit.Point, 204);
            this.labelInstruction.Location = new Point(13, 123);
            this.labelInstruction.Name = "labelInstruction";
            this.labelInstruction.Size = new Size(87, 17);
            this.labelInstruction.TabIndex = 6;
            this.labelInstruction.Text = "Поручается";
            this.richTxtInstruction.Anchor = (AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right);
            this.richTxtInstruction.DataBindings.Add(new Binding("Text", this.dataSetOrder, "tJ_Order.instruction", true));
            this.richTxtInstruction.Font = new Font("Microsoft Sans Serif", 10f, FontStyle.Regular, GraphicsUnit.Point, 204);
            this.richTxtInstruction.Location = new Point(16, 143);
            this.richTxtInstruction.Name = "richTxtInstruction";
            this.richTxtInstruction.Size = new Size(230, 86);
            this.richTxtInstruction.TabIndex = 7;
            this.richTxtInstruction.Text = "";
            this.richTxtInstruction.TextChanged += new EventHandler(this.richTxtInstruction_TextChanged);
            this.labelSR.AutoSize = true;
            this.labelSR.Location = new Point(44, 17);
            this.labelSR.Name = "labelSR";
            this.labelSR.Size = new Size(82, 13);
            this.labelSR.TabIndex = 8;
            this.labelSR.Text = "Сетевой район";
            this.cmbSR.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
            this.cmbSR.AutoCompleteSource = AutoCompleteSource.ListItems;
            this.cmbSR.DataBindings.Add(new Binding("SelectedValue", this.dataSetOrder, "tJ_Order.idSR", true));
            this.cmbSR.DataSource = this.dataSetOrder;
            this.cmbSR.DisplayMember = "tR_Classifier.Name";
            this.cmbSR.FormattingEnabled = true;
            this.cmbSR.Location = new Point(132, 14);
            this.cmbSR.Name = "cmbSR";
            this.cmbSR.Size = new Size(158, 21);
            this.cmbSR.TabIndex = 9;
            this.cmbSR.ValueMember = "tR_Classifier.Id";
            this.cmbSR.SelectedValueChanged += new EventHandler(this.cmbSR_SelectedValueChanged);
            this.label6.AutoSize = true;
            this.label6.Location = new Point(16, 67);
            this.label6.Name = "label6";
            this.label6.Size = new Size(110, 13);
            this.label6.TabIndex = 10;
            this.label6.Text = "Руководитель работ";
            this.labelAccept.AutoSize = true;
            this.labelAccept.Location = new Point(44, 95);
            this.labelAccept.Name = "labelAccept";
            this.labelAccept.Size = new Size(80, 13);
            this.labelAccept.TabIndex = 11;
            this.labelAccept.Text = "Допускающий";
            this.label8.AutoSize = true;
            this.label8.Location = new Point(44, 124);
            this.label8.Name = "label8";
            this.label8.Size = new Size(82, 13);
            this.label8.TabIndex = 12;
            this.label8.Text = "Наблюдающий";
            this.labelMaker.AutoSize = true;
            this.labelMaker.Location = new Point(6, 152);
            this.labelMaker.Name = "labelMaker";
            this.labelMaker.Size = new Size(118, 13);
            this.labelMaker.TabIndex = 13;
            this.labelMaker.Text = "Производитель работ";
            this.label10.AutoSize = true;
            this.label10.Location = new Point(307, 17);
            this.label10.Name = "label10";
            this.label10.Size = new Size(87, 13);
            this.label10.TabIndex = 14;
            this.label10.Text = "Члены бригады";
            this.label11.AutoSize = true;
            this.label11.Location = new Point(13, 232);
            this.label11.Name = "label11";
            this.label11.Size = new Size(114, 13);
            this.label11.TabIndex = 15;
            this.label11.Text = "Отдельные указания";
            this.richTxtOtrherInstructions.Anchor = (AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right);
            this.richTxtOtrherInstructions.DataBindings.Add(new Binding("Text", this.dataSetOrder, "tJ_Order.otherInstruction", true));
            this.richTxtOtrherInstructions.Location = new Point(16, 248);
            this.richTxtOtrherInstructions.Name = "richTxtOtrherInstructions";
            this.richTxtOtrherInstructions.Size = new Size(230, 85);
            this.richTxtOtrherInstructions.TabIndex = 16;
            this.richTxtOtrherInstructions.Text = "";
            this.labelOutput.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
            this.labelOutput.AutoSize = true;
            this.labelOutput.Location = new Point(13, 408);
            this.labelOutput.Name = "labelOutput";
            this.labelOutput.Size = new Size(74, 13);
            this.labelOutput.TabIndex = 17;
            this.labelOutput.Text = "Наряд выдал";
            this.cmbAcceptWorker.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
            this.cmbAcceptWorker.AutoCompleteSource = AutoCompleteSource.ListItems;
            this.cmbAcceptWorker.DataBindings.Add(new Binding("SelectedValue", this.dataSetOrder, "tJ_Order.acceptworker", true));
            this.cmbAcceptWorker.DisplayMember = "FIO";
            this.cmbAcceptWorker.FormattingEnabled = true;
            this.cmbAcceptWorker.Location = new Point(132, 92);
            this.cmbAcceptWorker.Name = "cmbAcceptWorker";
            this.cmbAcceptWorker.Size = new Size(133, 21);
            this.cmbAcceptWorker.TabIndex = 21;
            this.cmbAcceptWorker.ValueMember = "id";
            this.cmbAcceptWorker.SelectedIndexChanged += new EventHandler(this.cmbAcceptWorker_SelectedIndexChanged);
            this.cmbAcceptWorker.SelectedValueChanged += new EventHandler(this.cmbAcceptWorker_SelectedValueChanged);
            this.cmbAcceptWorker.TextChanged += new EventHandler(this.cmbAcceptWorker_TextChanged);
            this.dateTimePickerDateBegin.Anchor = (AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right);
            this.dateTimePickerDateBegin.CustomFormat = "dd:MM:yyyy HH:mm";
            this.dateTimePickerDateBegin.DataBindings.Add(new Binding("Value", this.dataSetOrder, "tJ_Order.dateBegin", true));
            this.dateTimePickerDateBegin.Format = DateTimePickerFormat.Custom;
            this.dateTimePickerDateBegin.Location = new Point(115, 71);
            this.dateTimePickerDateBegin.Name = "dateTimePickerDateBegin";
            this.dateTimePickerDateBegin.Size = new Size(131, 20);
            this.dateTimePickerDateBegin.TabIndex = 24;
            this.dateTimePickerDateBegin.Value = new DateTime(2012, 6, 5, 9, 25, 13, 282);
            this.dateTimePickerDateBegin.ValueChanged += new EventHandler(this.dateTimePickerDateBegin_ValueChanged);
            this.dateTimePickerDateEnd.Anchor = (AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right);
            this.dateTimePickerDateEnd.CustomFormat = "dd:MM:yyyy HH:mm";
            this.dateTimePickerDateEnd.DataBindings.Add(new Binding("Value", this.dataSetOrder, "tJ_Order.dateEnd", true));
            this.dateTimePickerDateEnd.Format = DateTimePickerFormat.Custom;
            this.dateTimePickerDateEnd.Location = new Point(115, 93);
            this.dateTimePickerDateEnd.Name = "dateTimePickerDateEnd";
            this.dateTimePickerDateEnd.Size = new Size(131, 20);
            this.dateTimePickerDateEnd.TabIndex = 25;
            this.dateTimePickerDateEnd.Value = new DateTime(2012, 6, 5, 9, 28, 51, 995);
            this.dateTimePickerDateEnd.ValueChanged += new EventHandler(this.dateTimePickerDateEnd_ValueChanged);
            this.cmbHeadWorker.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
            this.cmbHeadWorker.AutoCompleteSource = AutoCompleteSource.ListItems;
            this.cmbHeadWorker.DataBindings.Add(new Binding("SelectedValue", this.dataSetOrder, "tJ_Order.headworker", true));
            this.cmbHeadWorker.DisplayMember = "FIO";
            this.cmbHeadWorker.FormattingEnabled = true;
            this.cmbHeadWorker.Location = new Point(132, 64);
            this.cmbHeadWorker.Name = "cmbHeadWorker";
            this.cmbHeadWorker.Size = new Size(133, 21);
            this.cmbHeadWorker.TabIndex = 26;
            this.cmbHeadWorker.ValueMember = "id";
            this.cmbHeadWorker.SelectedIndexChanged += new EventHandler(this.cmbHeadWorker_SelectedIndexChanged);
            this.cmbHeadWorker.TextChanged += new EventHandler(this.cmbHeadWorker_TextChanged);
            this.cmbWatchWorker.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
            this.cmbWatchWorker.AutoCompleteSource = AutoCompleteSource.ListItems;
            this.cmbWatchWorker.DataBindings.Add(new Binding("SelectedValue", this.dataSetOrder, "tJ_Order.watchWorker", true));
            this.cmbWatchWorker.DisplayMember = "FIO";
            this.cmbWatchWorker.FormattingEnabled = true;
            this.cmbWatchWorker.Location = new Point(132, 121);
            this.cmbWatchWorker.Name = "cmbWatchWorker";
            this.cmbWatchWorker.Size = new Size(133, 21);
            this.cmbWatchWorker.TabIndex = 27;
            this.cmbWatchWorker.ValueMember = "id";
            this.cmbWatchWorker.SelectedIndexChanged += new EventHandler(this.cmbWatchWorker_SelectedIndexChanged);
            this.cmbWatchWorker.TextChanged += new EventHandler(this.cmbWatchWorker_TextChanged);
            this.cmbMakerWorker.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
            this.cmbMakerWorker.AutoCompleteSource = AutoCompleteSource.ListItems;
            this.cmbMakerWorker.DataBindings.Add(new Binding("SelectedValue", this.dataSetOrder, "tJ_Order.makerWorker", true));
            this.cmbMakerWorker.DisplayMember = "FIO";
            this.cmbMakerWorker.FormattingEnabled = true;
            this.cmbMakerWorker.Location = new Point(132, 149);
            this.cmbMakerWorker.Name = "cmbMakerWorker";
            this.cmbMakerWorker.Size = new Size(133, 21);
            this.cmbMakerWorker.TabIndex = 28;
            this.cmbMakerWorker.ValueMember = "id";
            this.cmbMakerWorker.SelectedIndexChanged += new EventHandler(this.cmbMakerWorker_SelectedIndexChanged);
            this.cmbMakerWorker.SelectedValueChanged += new EventHandler(this.cmbMakerWorker_SelectedValueChanged);
            this.cmbMakerWorker.TextChanged += new EventHandler(this.cmbMakerWorker_TextChanged);
            this.cmbOutputWorker.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right);
            this.cmbOutputWorker.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
            this.cmbOutputWorker.AutoCompleteSource = AutoCompleteSource.ListItems;
            this.cmbOutputWorker.DataBindings.Add(new Binding("SelectedValue", this.dataSetOrder, "tJ_Order.outputWorker", true));
            this.cmbOutputWorker.DisplayMember = "FIO";
            this.cmbOutputWorker.FormattingEnabled = true;
            this.cmbOutputWorker.Location = new Point(93, 405);
            this.cmbOutputWorker.Name = "cmbOutputWorker";
            this.cmbOutputWorker.Size = new Size(124, 21);
            this.cmbOutputWorker.TabIndex = 29;
            this.cmbOutputWorker.ValueMember = "id";
            this.cmbOutputWorker.SelectedIndexChanged += new EventHandler(this.cmbOutputWorker_SelectedIndexChanged);
            this.cmbOutputWorker.SelectedValueChanged += new EventHandler(this.cmbOutputWorker_SelectedValueChanged);
            this.cmbOutputWorker.TextChanged += new EventHandler(this.cmbOutputWorker_TextChanged);
            this.dateTimePickerDateOutput.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right);
            this.dateTimePickerDateOutput.CustomFormat = "dd:MM:yyyy HH:mm";
            this.dateTimePickerDateOutput.DataBindings.Add(new Binding("Value", this.dataSetOrder, "tJ_Order.dateOutput", true));
            this.dateTimePickerDateOutput.Format = DateTimePickerFormat.Custom;
            this.dateTimePickerDateOutput.Location = new Point(93, 431);
            this.dateTimePickerDateOutput.Name = "dateTimePickerDateOutput";
            this.dateTimePickerDateOutput.Size = new Size(152, 20);
            this.dateTimePickerDateOutput.TabIndex = 30;
            this.dateTimePickerDateOutput.Value = new DateTime(2012, 6, 5, 9, 28, 51, 995);
            this.dateTimePickerDateOutput.ValueChanged += new EventHandler(this.dateTimePickerDateOutput_ValueChanged);
            this.buttonSave.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
            this.buttonSave.Location = new Point(16, 517);
            this.buttonSave.Name = "buttonSave";
            this.buttonSave.Size = new Size(75, 23);
            this.buttonSave.TabIndex = 31;
            this.buttonSave.Text = "Сохранить";
            this.buttonSave.UseVisualStyleBackColor = true;
            this.buttonSave.Click += new EventHandler(this.buttonSave_Click);
            this.buttonRegister.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
            this.buttonRegister.Location = new Point(97, 517);
            this.buttonRegister.Name = "buttonRegister";
            this.buttonRegister.Size = new Size(114, 23);
            this.buttonRegister.TabIndex = 32;
            this.buttonRegister.Text = "Зарегистрировать";
            this.buttonRegister.UseVisualStyleBackColor = true;
            this.buttonRegister.Click += new EventHandler(this.buttonRegister_Click);
            this.dgvBrigade.Anchor = (AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right);
            this.dgvBrigade.AutoGenerateColumns = false;
            dataGridViewCellStyle.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle.BackColor = SystemColors.Control;
            dataGridViewCellStyle.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 204);
            dataGridViewCellStyle.ForeColor = SystemColors.WindowText;
            dataGridViewCellStyle.SelectionBackColor = SystemColors.Highlight;
            dataGridViewCellStyle.SelectionForeColor = SystemColors.HighlightText;
            dataGridViewCellStyle.WrapMode = DataGridViewTriState.True;
            this.dgvBrigade.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle;
            this.dgvBrigade.ColumnHeadersVisible = false;
            this.dgvBrigade.Columns.AddRange(new DataGridViewColumn[]
            {
            this.idDataGridViewTextBoxColumn,
            this.idOrderDataGridViewTextBoxColumn,
            this.brigadeWorkerColumn,
            this.GroupElectricalTxtColumn,
            this.idJobTitleDgvColumn,
            this.isUnderstudyDgvColumn
            });
            this.dgvBrigade.DataMember = "tJ_OrderBrigade";
            this.dgvBrigade.DataSource = this.dataSetOrder;
            dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = SystemColors.Window;
            dataGridViewCellStyle2.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 204);
            dataGridViewCellStyle2.ForeColor = SystemColors.ControlText;
            dataGridViewCellStyle2.SelectionBackColor = SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = DataGridViewTriState.False;
            this.dgvBrigade.DefaultCellStyle = dataGridViewCellStyle2;
            this.dgvBrigade.Location = new Point(296, 36);
            this.dgvBrigade.Name = "dgvBrigade";
            dataGridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = SystemColors.Control;
            dataGridViewCellStyle3.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 204);
            dataGridViewCellStyle3.ForeColor = SystemColors.WindowText;
            dataGridViewCellStyle3.SelectionBackColor = SystemColors.Highlight;
            dataGridViewCellStyle3.SelectionForeColor = SystemColors.HighlightText;
            dataGridViewCellStyle3.WrapMode = DataGridViewTriState.True;
            this.dgvBrigade.RowHeadersDefaultCellStyle = dataGridViewCellStyle3;
            this.dgvBrigade.RowHeadersWidth = 30;
            this.dgvBrigade.RowHeadersWidthSizeMode = DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            this.dgvBrigade.Size = new Size(310, 134);
            this.dgvBrigade.TabIndex = 33;
            this.dgvBrigade.CellEndEdit += new DataGridViewCellEventHandler(this.dgvBrigade_CellEndEdit);
            this.dgvBrigade.CellValueChanged += new DataGridViewCellEventHandler(this.dgvBrigade_CellValueChanged);
            this.dgvBrigade.DataError += new DataGridViewDataErrorEventHandler(this.dataGridView_DataError);
            this.dgvBrigade.EditingControlShowing += new DataGridViewEditingControlShowingEventHandler(this.dgvBrigade_EditingControlShowing);
            this.dgvBrigade.RowsAdded += new DataGridViewRowsAddedEventHandler(this.dgvBrigade_RowsAdded);
            this.dgvBrigade.KeyDown += new KeyEventHandler(this.dgvBrigade_KeyDown);
            this.idDataGridViewTextBoxColumn.DataPropertyName = "id";
            this.idDataGridViewTextBoxColumn.HeaderText = "id";
            this.idDataGridViewTextBoxColumn.Name = "idDataGridViewTextBoxColumn";
            this.idDataGridViewTextBoxColumn.ReadOnly = true;
            this.idDataGridViewTextBoxColumn.Visible = false;
            this.idOrderDataGridViewTextBoxColumn.DataPropertyName = "idOrder";
            this.idOrderDataGridViewTextBoxColumn.HeaderText = "idOrder";
            this.idOrderDataGridViewTextBoxColumn.Name = "idOrderDataGridViewTextBoxColumn";
            this.idOrderDataGridViewTextBoxColumn.Visible = false;
            this.brigadeWorkerColumn.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.brigadeWorkerColumn.DataPropertyName = "idWorker";
            this.brigadeWorkerColumn.HeaderText = "idWorker";
            this.brigadeWorkerColumn.Name = "brigadeWorkerColumn";
            this.brigadeWorkerColumn.Resizable = DataGridViewTriState.True;
            this.brigadeWorkerColumn.SortMode = DataGridViewColumnSortMode.Automatic;
            dataGridViewCellStyle4.BackColor = Color.LightGray;
            this.GroupElectricalTxtColumn.DefaultCellStyle = dataGridViewCellStyle4;
            this.GroupElectricalTxtColumn.HeaderText = "Гр";
            this.GroupElectricalTxtColumn.Name = "GroupElectricalTxtColumn";
            this.GroupElectricalTxtColumn.ReadOnly = true;
            this.GroupElectricalTxtColumn.Width = 25;
            this.idJobTitleDgvColumn.DataPropertyName = "idJobTitle";
            this.idJobTitleDgvColumn.HeaderText = "должн.";
            this.idJobTitleDgvColumn.Name = "idJobTitleDgvColumn";
            this.isUnderstudyDgvColumn.DataPropertyName = "isUnderstudy";
            dataGridViewCellStyle5.Alignment = DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle5.BackColor = Color.LightGray;
            dataGridViewCellStyle5.NullValue = false;
            this.isUnderstudyDgvColumn.DefaultCellStyle = dataGridViewCellStyle5;
            this.isUnderstudyDgvColumn.HeaderText = "дублер";
            this.isUnderstudyDgvColumn.Name = "isUnderstudyDgvColumn";
            this.isUnderstudyDgvColumn.Width = 40;
            this.label13.AutoSize = true;
            this.label13.Location = new Point(147, 177);
            this.label13.Name = "label13";
            this.label13.Size = new Size(183, 13);
            this.label13.TabIndex = 34;
            this.label13.Text = "Меры по подготовке рабочих мест";
            this.dgvInstruction.AllowDrop = true;
            this.dgvInstruction.Anchor = (AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right);
            this.dgvInstruction.AutoGenerateColumns = false;
            this.dgvInstruction.AutoSizeRowsMode = DataGridViewAutoSizeRowsMode.DisplayedCells;
            dataGridViewCellStyle6.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = SystemColors.Control;
            dataGridViewCellStyle6.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 204);
            dataGridViewCellStyle6.ForeColor = SystemColors.WindowText;
            dataGridViewCellStyle6.SelectionBackColor = SystemColors.Highlight;
            dataGridViewCellStyle6.SelectionForeColor = SystemColors.HighlightText;
            dataGridViewCellStyle6.WrapMode = DataGridViewTriState.True;
            this.dgvInstruction.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle6;
            this.dgvInstruction.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvInstruction.Columns.AddRange(new DataGridViewColumn[]
            {
            this.idDataGridViewTextBoxColumn1,
            this.idOrderDgvColumnInstruction,
            this.nameObjDataGridViewTextBoxColumn,
            this.instructionDataGridViewTextBoxColumn,
            this.recnumDataGridViewTextBoxColumn
            });
            this.dgvInstruction.DataMember = "tJ_OrderInstruction";
            this.dgvInstruction.DataSource = this.dataSetOrder;
            dataGridViewCellStyle7.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle7.BackColor = SystemColors.Window;
            dataGridViewCellStyle7.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 204);
            dataGridViewCellStyle7.ForeColor = SystemColors.ControlText;
            dataGridViewCellStyle7.SelectionBackColor = SystemColors.Highlight;
            dataGridViewCellStyle7.SelectionForeColor = SystemColors.HighlightText;
            dataGridViewCellStyle7.WrapMode = DataGridViewTriState.False;
            this.dgvInstruction.DefaultCellStyle = dataGridViewCellStyle7;
            this.dgvInstruction.Location = new Point(9, 193);
            this.dgvInstruction.Name = "dgvInstruction";
            dataGridViewCellStyle8.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle8.BackColor = SystemColors.Control;
            dataGridViewCellStyle8.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 204);
            dataGridViewCellStyle8.ForeColor = SystemColors.WindowText;
            dataGridViewCellStyle8.SelectionBackColor = SystemColors.Highlight;
            dataGridViewCellStyle8.SelectionForeColor = SystemColors.HighlightText;
            dataGridViewCellStyle8.WrapMode = DataGridViewTriState.True;
            this.dgvInstruction.RowHeadersDefaultCellStyle = dataGridViewCellStyle8;
            dataGridViewCellStyle9.WrapMode = DataGridViewTriState.True;
            this.dgvInstruction.RowsDefaultCellStyle = dataGridViewCellStyle9;
            this.dgvInstruction.RowTemplate.Height = 44;
            this.dgvInstruction.RowTemplate.Resizable = DataGridViewTriState.True;
            this.dgvInstruction.Size = new Size(597, 169);
            this.dgvInstruction.TabIndex = 35;
            this.dgvInstruction.CellDoubleClick += new DataGridViewCellEventHandler(this.dgvInstruction_CellDoubleClick);
            this.dgvInstruction.CellValueChanged += new DataGridViewCellEventHandler(this.dgvInstruction_CellValueChanged);
            this.dgvInstruction.DataError += new DataGridViewDataErrorEventHandler(this.dgvInstruction_DataError);
            this.idDataGridViewTextBoxColumn1.DataPropertyName = "id";
            this.idDataGridViewTextBoxColumn1.HeaderText = "id";
            this.idDataGridViewTextBoxColumn1.Name = "idDataGridViewTextBoxColumn1";
            this.idDataGridViewTextBoxColumn1.ReadOnly = true;
            this.idDataGridViewTextBoxColumn1.Visible = false;
            this.idOrderDgvColumnInstruction.DataPropertyName = "idOrder";
            this.idOrderDgvColumnInstruction.HeaderText = "idOrder";
            this.idOrderDgvColumnInstruction.Name = "idOrderDgvColumnInstruction";
            this.idOrderDgvColumnInstruction.Visible = false;
            this.nameObjDataGridViewTextBoxColumn.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.nameObjDataGridViewTextBoxColumn.DataPropertyName = "NameObj";
            this.nameObjDataGridViewTextBoxColumn.FillWeight = 35f;
            this.nameObjDataGridViewTextBoxColumn.HeaderText = "Наименование электроустановок";
            this.nameObjDataGridViewTextBoxColumn.Name = "nameObjDataGridViewTextBoxColumn";
            this.nameObjDataGridViewTextBoxColumn.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.instructionDataGridViewTextBoxColumn.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.instructionDataGridViewTextBoxColumn.DataPropertyName = "Instruction";
            this.instructionDataGridViewTextBoxColumn.FillWeight = 65f;
            this.instructionDataGridViewTextBoxColumn.HeaderText = "Что должно быть отключено и где заземлено";
            this.instructionDataGridViewTextBoxColumn.Name = "instructionDataGridViewTextBoxColumn";
            this.instructionDataGridViewTextBoxColumn.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.recnumDataGridViewTextBoxColumn.DataPropertyName = "rec_num";
            this.recnumDataGridViewTextBoxColumn.HeaderText = "rec_num";
            this.recnumDataGridViewTextBoxColumn.Name = "recnumDataGridViewTextBoxColumn";
            this.recnumDataGridViewTextBoxColumn.Visible = false;
            this.dgvResolution.AllowUserToAddRows = false;
            this.dgvResolution.AllowUserToDeleteRows = false;
            this.dgvResolution.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right);
            this.dgvResolution.AutoGenerateColumns = false;
            this.dgvResolution.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvResolution.Columns.AddRange(new DataGridViewColumn[]
            {
            this.idDataGridViewTextBoxColumn2,
            this.idOrderDataGridViewTextBoxColumn1,
            this.workerResolutionColumn,
            this.dateBeginDataGridViewTextBoxColumn,
            this.dateEndDataGridViewTextBoxColumn
            });
            this.dgvResolution.DataMember = "tJ_OrderResolution";
            this.dgvResolution.DataSource = this.dataSetOrder;
            this.dgvResolution.Location = new Point(9, 381);
            this.dgvResolution.Name = "dgvResolution";
            this.dgvResolution.ReadOnly = true;
            this.dgvResolution.RowHeadersVisible = false;
            this.dgvResolution.RowTemplate.Resizable = DataGridViewTriState.False;
            this.dgvResolution.Size = new Size(421, 117);
            this.dgvResolution.TabIndex = 36;
            this.dgvResolution.DataError += new DataGridViewDataErrorEventHandler(this.dataGridView_DataError);
            this.idDataGridViewTextBoxColumn2.DataPropertyName = "id";
            this.idDataGridViewTextBoxColumn2.HeaderText = "id";
            this.idDataGridViewTextBoxColumn2.Name = "idDataGridViewTextBoxColumn2";
            this.idDataGridViewTextBoxColumn2.ReadOnly = true;
            this.idDataGridViewTextBoxColumn2.Visible = false;
            this.idOrderDataGridViewTextBoxColumn1.DataPropertyName = "idOrder";
            this.idOrderDataGridViewTextBoxColumn1.HeaderText = "idOrder";
            this.idOrderDataGridViewTextBoxColumn1.Name = "idOrderDataGridViewTextBoxColumn1";
            this.idOrderDataGridViewTextBoxColumn1.ReadOnly = true;
            this.idOrderDataGridViewTextBoxColumn1.Visible = false;
            this.workerResolutionColumn.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.workerResolutionColumn.DataPropertyName = "idWorker";
            this.workerResolutionColumn.DisplayStyle = DataGridViewComboBoxDisplayStyle.Nothing;
            this.workerResolutionColumn.FillWeight = 40f;
            this.workerResolutionColumn.FlatStyle = FlatStyle.System;
            this.workerResolutionColumn.HeaderText = "Выдал";
            this.workerResolutionColumn.Name = "workerResolutionColumn";
            this.workerResolutionColumn.ReadOnly = true;
            this.workerResolutionColumn.Resizable = DataGridViewTriState.True;
            this.dateBeginDataGridViewTextBoxColumn.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.dateBeginDataGridViewTextBoxColumn.DataPropertyName = "DateBegin";
            this.dateBeginDataGridViewTextBoxColumn.FillWeight = 30f;
            this.dateBeginDataGridViewTextBoxColumn.HeaderText = "Начало работ";
            this.dateBeginDataGridViewTextBoxColumn.Name = "dateBeginDataGridViewTextBoxColumn";
            this.dateBeginDataGridViewTextBoxColumn.ReadOnly = true;
            this.dateBeginDataGridViewTextBoxColumn.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.dateEndDataGridViewTextBoxColumn.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.dateEndDataGridViewTextBoxColumn.DataPropertyName = "DateEnd";
            this.dateEndDataGridViewTextBoxColumn.FillWeight = 30f;
            this.dateEndDataGridViewTextBoxColumn.HeaderText = "Работа закончена";
            this.dateEndDataGridViewTextBoxColumn.Name = "dateEndDataGridViewTextBoxColumn";
            this.dateEndDataGridViewTextBoxColumn.ReadOnly = true;
            this.dateEndDataGridViewTextBoxColumn.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.cmbWorkerResolution.Anchor = (AnchorStyles.Bottom | AnchorStyles.Right);
            this.cmbWorkerResolution.Enabled = false;
            this.cmbWorkerResolution.FormattingEnabled = true;
            this.cmbWorkerResolution.Location = new Point(436, 381);
            this.cmbWorkerResolution.Name = "cmbWorkerResolution";
            this.cmbWorkerResolution.Size = new Size(170, 21);
            this.cmbWorkerResolution.TabIndex = 37;
            this.cmbWorkerResolution.SelectedIndexChanged += new EventHandler(this.cmbWorkerResolution_SelectedIndexChanged);
            this.dateTimePickerResolution.Anchor = (AnchorStyles.Bottom | AnchorStyles.Right);
            this.dateTimePickerResolution.CustomFormat = "dd:MM:yyyy HH:mm";
            this.dateTimePickerResolution.Enabled = false;
            this.dateTimePickerResolution.Format = DateTimePickerFormat.Custom;
            this.dateTimePickerResolution.Location = new Point(436, 408);
            this.dateTimePickerResolution.Name = "dateTimePickerResolution";
            this.dateTimePickerResolution.Size = new Size(170, 20);
            this.dateTimePickerResolution.TabIndex = 38;
            this.dateTimePickerResolution.Value = new DateTime(2012, 6, 5, 9, 28, 51, 995);
            this.buttonResolution.Anchor = (AnchorStyles.Bottom | AnchorStyles.Right);
            this.buttonResolution.Enabled = false;
            this.buttonResolution.Location = new Point(472, 434);
            this.buttonResolution.Name = "buttonResolution";
            this.buttonResolution.Size = new Size(134, 23);
            this.buttonResolution.TabIndex = 39;
            this.buttonResolution.Text = "Выдать разрешение";
            this.buttonResolution.UseVisualStyleBackColor = true;
            this.buttonResolution.Click += new EventHandler(this.buttonResolution_Click);
            this.buttonCloseOrder.Anchor = (AnchorStyles.Bottom | AnchorStyles.Right);
            this.buttonCloseOrder.Enabled = false;
            this.buttonCloseOrder.Location = new Point(472, 517);
            this.buttonCloseOrder.Name = "buttonCloseOrder";
            this.buttonCloseOrder.Size = new Size(134, 23);
            this.buttonCloseOrder.TabIndex = 42;
            this.buttonCloseOrder.Text = "Закрыть наряд";
            this.buttonCloseOrder.UseVisualStyleBackColor = true;
            this.buttonCloseOrder.Click += new EventHandler(this.buttonCloseOrder_Click);
            this.dateTimePickerClose.Anchor = (AnchorStyles.Bottom | AnchorStyles.Right);
            this.dateTimePickerClose.CustomFormat = "dd:MM:yyyy HH:mm";
            this.dateTimePickerClose.Enabled = false;
            this.dateTimePickerClose.Format = DateTimePickerFormat.Custom;
            this.dateTimePickerClose.Location = new Point(260, 520);
            this.dateTimePickerClose.Name = "dateTimePickerClose";
            this.dateTimePickerClose.Size = new Size(170, 20);
            this.dateTimePickerClose.TabIndex = 41;
            this.dateTimePickerClose.Value = new DateTime(2012, 6, 5, 9, 28, 51, 995);
            this.cmbCloseWorker.Anchor = (AnchorStyles.Bottom | AnchorStyles.Right);
            this.cmbCloseWorker.Enabled = false;
            this.cmbCloseWorker.FormattingEnabled = true;
            this.cmbCloseWorker.Location = new Point(84, 519);
            this.cmbCloseWorker.Name = "cmbCloseWorker";
            this.cmbCloseWorker.Size = new Size(170, 21);
            this.cmbCloseWorker.TabIndex = 40;
            this.cmbCloseWorker.SelectedIndexChanged += new EventHandler(this.cmbCloseWorker_SelectedIndexChanged);
            this.toolStripReport.GripStyle = ToolStripGripStyle.Hidden;
            this.toolStripReport.Items.AddRange(new ToolStripItem[]
            {
            this.toolBtnReport,
            this.toolBtnCopyOrder
            });
            this.toolStripReport.Location = new Point(0, 0);
            this.toolStripReport.Name = "toolStripReport";
            this.toolStripReport.Size = new Size(252, 25);
            this.toolStripReport.TabIndex = 43;
            this.toolStripReport.Text = "toolStrip1";
            this.toolBtnReport.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnReport.Enabled = false;
            this.toolBtnReport.Image = Properties.Resources.microsoftoffice2007excel_7581;
            this.toolBtnReport.ImageTransparentColor = Color.Magenta;
            this.toolBtnReport.Name = "toolBtnReport";
            this.toolBtnReport.Size = new Size(23, 22);
            this.toolBtnReport.Text = "Печать наряда";
            this.toolBtnReport.Click += new EventHandler(this.toolBtnReport_Click);
            this.toolBtnCopyOrder.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnCopyOrder.Enabled = false;
            this.toolBtnCopyOrder.Image = Properties.Resources.CopyBuffer;
            this.toolBtnCopyOrder.ImageTransparentColor = Color.Magenta;
            this.toolBtnCopyOrder.Name = "toolBtnCopyOrder";
            this.toolBtnCopyOrder.Size = new Size(23, 22);
            this.toolBtnCopyOrder.Text = "Копировать наряд";
            this.toolBtnCopyOrder.Click += new EventHandler(this.toolBtnCopyOrder_Click);
            this.splitContainer.Dock = DockStyle.Fill;
            this.splitContainer.FixedPanel = FixedPanel.Panel1;
            this.splitContainer.Location = new Point(0, 0);
            this.splitContainer.Name = "splitContainer";
            this.splitContainer.Panel1.Controls.Add(this.labelOutputDate);
            this.splitContainer.Panel1.Controls.Add(this.panelExtension);
            this.splitContainer.Panel1.Controls.Add(this.txtOutputWorker);
            this.splitContainer.Panel1.Controls.Add(this.toolStripScheme);
            this.splitContainer.Panel1.Controls.Add(this.listBoxLinkScmObjects);
            this.splitContainer.Panel1.Controls.Add(this.buttonSave);
            this.splitContainer.Panel1.Controls.Add(this.toolStripReport);
            this.splitContainer.Panel1.Controls.Add(this.label1);
            this.splitContainer.Panel1.Controls.Add(this.txtNumOrder);
            this.splitContainer.Panel1.Controls.Add(this.labelDateBegin);
            this.splitContainer.Panel1.Controls.Add(this.labelDateEnd);
            this.splitContainer.Panel1.Controls.Add(this.labelInstruction);
            this.splitContainer.Panel1.Controls.Add(this.richTxtInstruction);
            this.splitContainer.Panel1.Controls.Add(this.label11);
            this.splitContainer.Panel1.Controls.Add(this.richTxtOtrherInstructions);
            this.splitContainer.Panel1.Controls.Add(this.labelOutput);
            this.splitContainer.Panel1.Controls.Add(this.dateTimePickerDateBegin);
            this.splitContainer.Panel1.Controls.Add(this.dateTimePickerDateEnd);
            this.splitContainer.Panel1.Controls.Add(this.buttonRegister);
            this.splitContainer.Panel1.Controls.Add(this.cmbOutputWorker);
            this.splitContainer.Panel1.Controls.Add(this.dateTimePickerDateOutput);
            this.splitContainer.Panel2.Controls.Add(this.labelDivision);
            this.splitContainer.Panel2.Controls.Add(this.cmbDivision);
            this.splitContainer.Panel2.Controls.Add(this.label4);
            this.splitContainer.Panel2.Controls.Add(this.txtMakerWorker);
            this.splitContainer.Panel2.Controls.Add(this.txtWatchWorker);
            this.splitContainer.Panel2.Controls.Add(this.txtAcceptWorker);
            this.splitContainer.Panel2.Controls.Add(this.txtHeadWorker);
            this.splitContainer.Panel2.Controls.Add(this.label2);
            this.splitContainer.Panel2.Controls.Add(this.dgvBrigade);
            this.splitContainer.Panel2.Controls.Add(this.buttonCloseOrder);
            this.splitContainer.Panel2.Controls.Add(this.labelSR);
            this.splitContainer.Panel2.Controls.Add(this.dateTimePickerClose);
            this.splitContainer.Panel2.Controls.Add(this.cmbSR);
            this.splitContainer.Panel2.Controls.Add(this.cmbCloseWorker);
            this.splitContainer.Panel2.Controls.Add(this.label6);
            this.splitContainer.Panel2.Controls.Add(this.buttonResolution);
            this.splitContainer.Panel2.Controls.Add(this.labelAccept);
            this.splitContainer.Panel2.Controls.Add(this.dateTimePickerResolution);
            this.splitContainer.Panel2.Controls.Add(this.label8);
            this.splitContainer.Panel2.Controls.Add(this.cmbWorkerResolution);
            this.splitContainer.Panel2.Controls.Add(this.labelMaker);
            this.splitContainer.Panel2.Controls.Add(this.dgvResolution);
            this.splitContainer.Panel2.Controls.Add(this.label10);
            this.splitContainer.Panel2.Controls.Add(this.dgvInstruction);
            this.splitContainer.Panel2.Controls.Add(this.cmbAcceptWorker);
            this.splitContainer.Panel2.Controls.Add(this.label13);
            this.splitContainer.Panel2.Controls.Add(this.cmbHeadWorker);
            this.splitContainer.Panel2.Controls.Add(this.cmbWatchWorker);
            this.splitContainer.Panel2.Controls.Add(this.cmbMakerWorker);
            this.splitContainer.Size = new Size(876, 543);
            this.splitContainer.SplitterDistance = 252;
            this.splitContainer.TabIndex = 44;
            this.labelOutputDate.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
            this.labelOutputDate.AutoSize = true;
            this.labelOutputDate.Location = new Point(13, 437);
            this.labelOutputDate.Name = "labelOutputDate";
            this.labelOutputDate.Size = new Size(77, 13);
            this.labelOutputDate.TabIndex = 50;
            this.labelOutputDate.Text = "Дата и время";
            this.panelExtension.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right);
            this.panelExtension.BackColor = SystemColors.ControlDark;
            this.panelExtension.Controls.Add(this.buttonExtension);
            this.panelExtension.Controls.Add(this.dateTimePickerDateEndExt);
            this.panelExtension.Controls.Add(this.cmbExtWorker);
            this.panelExtension.Controls.Add(this.label3);
            this.panelExtension.Enabled = false;
            this.panelExtension.Location = new Point(13, 457);
            this.panelExtension.Name = "panelExtension";
            this.panelExtension.Size = new Size(233, 54);
            this.panelExtension.TabIndex = 49;
            this.buttonExtension.Location = new Point(6, 27);
            this.buttonExtension.Name = "buttonExtension";
            this.buttonExtension.Size = new Size(75, 23);
            this.buttonExtension.TabIndex = 32;
            this.buttonExtension.Text = "Продлить";
            this.buttonExtension.UseVisualStyleBackColor = true;
            this.buttonExtension.Click += new EventHandler(this.buttonExtension_Click);
            this.dateTimePickerDateEndExt.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right);
            this.dateTimePickerDateEndExt.CustomFormat = "dd:MM:yyyy HH:mm";
            this.dateTimePickerDateEndExt.DataBindings.Add(new Binding("Value", this.dataSetOrder, "tJ_Order.dateEndExt", true));
            this.dateTimePickerDateEndExt.Format = DateTimePickerFormat.Custom;
            this.dateTimePickerDateEndExt.Location = new Point(93, 30);
            this.dateTimePickerDateEndExt.Name = "dateTimePickerDateEndExt";
            this.dateTimePickerDateEndExt.Size = new Size(137, 20);
            this.dateTimePickerDateEndExt.TabIndex = 31;
            this.dateTimePickerDateEndExt.Value = new DateTime(2012, 6, 5, 9, 28, 51, 995);
            this.cmbExtWorker.Anchor = (AnchorStyles.Left | AnchorStyles.Right);
            this.cmbExtWorker.AutoComplete = false;
            this.cmbExtWorker.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
            this.cmbExtWorker.AutoCompleteSource = AutoCompleteSource.ListItems;
            this.cmbExtWorker.AutoDropdown = false;
            this.cmbExtWorker.BackColorEven = Color.White;
            this.cmbExtWorker.BackColorOdd = Color.White;
            this.cmbExtWorker.ColumnNames = "";
            this.cmbExtWorker.ColumnWidthDefault = 75;
            this.cmbExtWorker.ColumnWidths = "0;120;0;30";
            this.cmbExtWorker.DataBindings.Add(new Binding("SelectedValue", this.dataSetOrder, "tJ_Order.extWorker", true));
            this.cmbExtWorker.DisplayMember = "id";
            this.cmbExtWorker.DrawMode = DrawMode.OwnerDrawVariable;
            this.cmbExtWorker.FormattingEnabled = true;
            this.cmbExtWorker.LinkedColumnIndex = 0;
            this.cmbExtWorker.LinkedTextBox = null;
            this.cmbExtWorker.Location = new Point(93, 3);
            this.cmbExtWorker.Name = "cmbExtWorker";
            this.cmbExtWorker.Size = new Size(137, 21);
            this.cmbExtWorker.TabIndex = 30;
            this.cmbExtWorker.ValueMember = "id";
            this.label3.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
            this.label3.AutoSize = true;
            this.label3.Location = new Point(3, 1);
            this.label3.Name = "label3";
            this.label3.Size = new Size(84, 13);
            this.label3.TabIndex = 18;
            this.label3.Text = "Наряд продлил";
            this.txtOutputWorker.Anchor = (AnchorStyles.Bottom | AnchorStyles.Right);
            this.txtOutputWorker.Location = new Point(218, 405);
            this.txtOutputWorker.Name = "txtOutputWorker";
            this.txtOutputWorker.ReadOnly = true;
            this.txtOutputWorker.Size = new Size(27, 20);
            this.txtOutputWorker.TabIndex = 48;
            this.toolStripScheme.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
            this.toolStripScheme.Dock = DockStyle.None;
            this.toolStripScheme.GripStyle = ToolStripGripStyle.Hidden;
            this.toolStripScheme.Items.AddRange(new ToolStripItem[]
            {
            this.toolBtnLinkSchmObj,
            this.toolBtnDelSchmObj,
            this.toolBtnViewSChmObj
            });
            this.toolStripScheme.LayoutStyle = ToolStripLayoutStyle.VerticalStackWithOverflow;
            this.toolStripScheme.Location = new Point(16, 331);
            this.toolStripScheme.Name = "toolStripScheme";
            this.toolStripScheme.Size = new Size(24, 71);
            this.toolStripScheme.TabIndex = 46;
            this.toolStripScheme.Text = "toolStrip1";
            this.toolBtnLinkSchmObj.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnLinkSchmObj.Image = Properties.Resources.ElementAdd;
            this.toolBtnLinkSchmObj.ImageTransparentColor = Color.Magenta;
            this.toolBtnLinkSchmObj.Name = "toolBtnLinkSchmObj";
            this.toolBtnLinkSchmObj.Size = new Size(22, 20);
            this.toolBtnLinkSchmObj.Text = "Привязать к схеме";
            this.toolBtnLinkSchmObj.Click += new EventHandler(this.toolBtnLinkSchmObj_Click);
            this.toolBtnDelSchmObj.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnDelSchmObj.Image = Properties.Resources.ElementDel;
            this.toolBtnDelSchmObj.ImageTransparentColor = Color.Magenta;
            this.toolBtnDelSchmObj.Name = "toolBtnDelSchmObj";
            this.toolBtnDelSchmObj.Size = new Size(22, 20);
            this.toolBtnDelSchmObj.Text = "Удалить";
            this.toolBtnDelSchmObj.Click += new EventHandler(this.toolBtnDelSchmObj_Click);
            this.toolBtnViewSChmObj.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnViewSChmObj.Enabled = false;
            this.toolBtnViewSChmObj.Image = Properties.Resources.ElementInformation;
            this.toolBtnViewSChmObj.ImageTransparentColor = Color.Magenta;
            this.toolBtnViewSChmObj.Name = "toolBtnViewSChmObj";
            this.toolBtnViewSChmObj.Size = new Size(22, 20);
            this.toolBtnViewSChmObj.Text = "Показать на схеме";
            this.toolBtnViewSChmObj.Click += new EventHandler(this.toolBtnViewSChmObj_Click);
            this.listBoxLinkScmObjects.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right);
            this.listBoxLinkScmObjects.FormattingEnabled = true;
            this.listBoxLinkScmObjects.Location = new Point(42, 333);
            this.listBoxLinkScmObjects.Name = "listBoxLinkScmObjects";
            this.listBoxLinkScmObjects.SelectionMode = SelectionMode.MultiSimple;
            this.listBoxLinkScmObjects.Size = new Size(203, 69);
            this.listBoxLinkScmObjects.Sorted = true;
            this.listBoxLinkScmObjects.TabIndex = 45;
            this.labelDivision.AutoSize = true;
            this.labelDivision.Location = new Point(39, 43);
            this.labelDivision.Name = "labelDivision";
            this.labelDivision.Size = new Size(87, 13);
            this.labelDivision.TabIndex = 50;
            this.labelDivision.Text = "Подразделение";
            this.cmbDivision.BackColor = SystemColors.Control;
            this.cmbDivision.DataBindings.Add(new Binding("SelectedValue", this.dataSetOrder, "tJ_Order.idDivision", true, DataSourceUpdateMode.OnPropertyChanged));
            this.cmbDivision.ForeColor = SystemColors.WindowText;
            this.cmbDivision.FormattingEnabled = true;
            this.cmbDivision.Location = new Point(132, 40);
            this.cmbDivision.Name = "cmbDivision";
            this.cmbDivision.ReadOnly = true;
            this.cmbDivision.ReadOnlyBackColor = SystemColors.Window;
            this.cmbDivision.ReadOnlyForeColor = SystemColors.WindowText;
            this.cmbDivision.Size = new Size(158, 21);
            this.cmbDivision.TabIndex = 49;
            this.label4.Anchor = (AnchorStyles.Top | AnchorStyles.Right);
            this.label4.AutoSize = true;
            this.label4.Location = new Point(561, 17);
            this.label4.Name = "label4";
            this.label4.Size = new Size(45, 13);
            this.label4.TabIndex = 48;
            this.label4.Text = "Дублер";
            this.txtMakerWorker.Location = new Point(263, 149);
            this.txtMakerWorker.Name = "txtMakerWorker";
            this.txtMakerWorker.ReadOnly = true;
            this.txtMakerWorker.Size = new Size(27, 20);
            this.txtMakerWorker.TabIndex = 47;
            this.txtWatchWorker.Location = new Point(263, 121);
            this.txtWatchWorker.Name = "txtWatchWorker";
            this.txtWatchWorker.ReadOnly = true;
            this.txtWatchWorker.Size = new Size(27, 20);
            this.txtWatchWorker.TabIndex = 46;
            this.txtAcceptWorker.Location = new Point(263, 92);
            this.txtAcceptWorker.Name = "txtAcceptWorker";
            this.txtAcceptWorker.ReadOnly = true;
            this.txtAcceptWorker.Size = new Size(27, 20);
            this.txtAcceptWorker.TabIndex = 45;
            this.txtHeadWorker.Location = new Point(263, 64);
            this.txtHeadWorker.Name = "txtHeadWorker";
            this.txtHeadWorker.ReadOnly = true;
            this.txtHeadWorker.Size = new Size(27, 20);
            this.txtHeadWorker.TabIndex = 44;
            this.label2.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
            this.label2.AutoSize = true;
            this.label2.Location = new Point(8, 365);
            this.label2.Name = "label2";
            this.label2.Size = new Size(386, 13);
            this.label2.TabIndex = 43;
            this.label2.Text = "Разрешение на подготовку рабочих мест и на допуск к выполнению работ";
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.ClientSize = new Size(876, 543);
            base.Controls.Add(this.splitContainer);
            base.KeyPreview = true;
            base.Name = "FormJournalOrderAddEdit";
            this.Text = "FormJournalOrderAddEdit";
            base.FormClosing += new FormClosingEventHandler(this.FormJournalOrderAddEdit_FormClosing);
            base.FormClosed += new FormClosedEventHandler(this.FormJournalOrderAddEdit_FormClosed);
            base.Load += new EventHandler(this.FormJournalOrderAddEdit_Load);
            base.KeyDown += new KeyEventHandler(this.FormJournalOrderAddEdit_KeyDown);
            ((ISupportInitialize)this.dataSetOrder).EndInit();
            ((ISupportInitialize)this.dgvBrigade).EndInit();
            ((ISupportInitialize)this.dgvInstruction).EndInit();
            ((ISupportInitialize)this.dgvResolution).EndInit();
            this.toolStripReport.ResumeLayout(false);
            this.toolStripReport.PerformLayout();
            this.splitContainer.Panel1.ResumeLayout(false);
            this.splitContainer.Panel1.PerformLayout();
            this.splitContainer.Panel2.ResumeLayout(false);
            this.splitContainer.Panel2.PerformLayout();
            this.splitContainer.ResumeLayout(false);
            this.panelExtension.ResumeLayout(false);
            this.panelExtension.PerformLayout();
            this.toolStripScheme.ResumeLayout(false);
            this.toolStripScheme.PerformLayout();
            base.ResumeLayout(false);
        }



        private Label label1;
        private TextBox txtNumOrder;
        private Label labelDateBegin;
        private Label labelDateEnd;
        private Label labelInstruction;
        private RichTextBox richTxtInstruction;
        private Label labelSR;
        private ComboBox cmbSR;
        private Label label6;
        private Label labelAccept;
        private Label label8;
        private Label labelMaker;
        private Label label10;
        private Label label11;
        private RichTextBox richTxtOtrherInstructions;
        private Label labelOutput;
        private ComboBox cmbAcceptWorker;
        private DataSet.DataSetOrder dataSetOrder;
        private NullableDateTimePicker dateTimePickerDateBegin;
        private NullableDateTimePicker dateTimePickerDateEnd;
        private ComboBox cmbHeadWorker;
        private ComboBox cmbWatchWorker;
        private ComboBox cmbMakerWorker;
        private ComboBox cmbOutputWorker;
        private NullableDateTimePicker dateTimePickerDateOutput;
        private Button buttonSave;
        private Button buttonRegister;
        private DataGridView dgvBrigade;
        private Label label13;
        private DataGridView dgvInstruction;
        private DataGridView dgvResolution;
        private ComboBox cmbWorkerResolution;
        private NullableDateTimePicker dateTimePickerResolution;
        private Button buttonResolution;
        private Button buttonCloseOrder;
        private NullableDateTimePicker dateTimePickerClose;
        private ComboBox cmbCloseWorker;
        private DataGridViewTextBoxColumn idDataGridViewTextBoxColumn2;
        private DataGridViewTextBoxColumn idOrderDataGridViewTextBoxColumn1;
        private DataGridViewComboBoxColumn workerResolutionColumn;
        private DataGridViewTextBoxColumn dateBeginDataGridViewTextBoxColumn;
        private DataGridViewTextBoxColumn dateEndDataGridViewTextBoxColumn;
        private ToolStrip toolStripReport;
        private ToolStripButton toolBtnReport;
        private SplitContainer splitContainer;
        private Label label2;
        private ToolStrip toolStripScheme;
        private ToolStripButton toolBtnLinkSchmObj;
        private ToolStripButton toolBtnDelSchmObj;
        private ToolStripButton toolBtnViewSChmObj;
        private ListBox listBoxLinkScmObjects;
        private ToolStripButton toolBtnCopyOrder;
        private TextBox txtHeadWorker;
        private TextBox txtOutputWorker;
        private TextBox txtMakerWorker;
        private TextBox txtWatchWorker;
        private TextBox txtAcceptWorker;
        private DataGridViewTextBoxColumn idDataGridViewTextBoxColumn1;
        private DataGridViewTextBoxColumn idOrderDgvColumnInstruction;
        private DataGridViewTextBoxColumn nameObjDataGridViewTextBoxColumn;
        private DataGridViewTextBoxColumn instructionDataGridViewTextBoxColumn;
        private DataGridViewTextBoxColumn recnumDataGridViewTextBoxColumn;
        private Panel panelExtension;
        private Button buttonExtension;
        private NullableDateTimePicker dateTimePickerDateEndExt;
        private MultiColumnComboBox cmbExtWorker;
        private Label label3;
        private Label labelOutputDate;
        private DataGridViewTextBoxColumn idDataGridViewTextBoxColumn;
        private DataGridViewTextBoxColumn idOrderDataGridViewTextBoxColumn;
        private DataGridViewComboBoxColumn brigadeWorkerColumn;
        private DataGridViewTextBoxColumn GroupElectricalTxtColumn;
        private DataGridViewComboBoxColumn idJobTitleDgvColumn;
        private DataGridViewCheckBoxColumn isUnderstudyDgvColumn;
        private Label label4;
        private Label labelDivision;
        private ComboBoxReadOnly cmbDivision;
    }
}