using ControlsLbr.DataGridViewExcelFilter;
using ControlsLbr.Scheme;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Windows.Forms;

namespace JournalOrder
{
    public partial class FormJournalOrder
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private System.ComponentModel.IContainer components = null;


        private void InitializeComponent()
        {
            this.components = new Container();
            DataGridViewCellStyle dataGridViewCellStyle = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle3 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle4 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle5 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle6 = new DataGridViewCellStyle();
            ComponentResourceManager resources = new ComponentResourceManager(typeof(FormJournalOrder));
            DataGridViewCellStyle dataGridViewCellStyle7 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle8 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle9 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle10 = new DataGridViewCellStyle();
            this.dgvOrder = new DataGridViewExcelFilter();
            this.numDgvColumn = new DataGridViewFilterTextBoxColumn();
            this.srNumDataGridViewTextBoxColumn = new DataGridViewFilterTextBoxColumn();
            this.dateOutputDataGridViewTextBoxColumn = new DataGridViewFilterDateTimePickerColumn();
            this.dateBeginDataGridViewTextBoxColumn = new DataGridViewFilterDateTimePickerColumn();
            this.dateEndDataGridViewTextBoxColumn = new DataGridViewFilterDateTimePickerColumn();
            this.registeredDgvColumn = new DataGridViewFilterCheckBoxColumn();
            this.outputMakerDataGridViewTextBoxColumn = new DataGridViewTextBoxColumn();
            this.instructionDataGridViewTextBoxColumn = new DataGridViewFilterTextBoxColumn();
            this.resolutionDataGridViewTextBoxColumn = new DataGridViewTextBoxColumn();
            this.srNameDataGridViewTextBoxColumn = new DataGridViewFilterTextBoxColumn();
            this.headFioDataGridViewTextBoxColumn = new DataGridViewFilterTextBoxColumn();
            this.acceptFIODataGridViewTextBoxColumn = new DataGridViewFilterTextBoxColumn();
            this.watchFIODataGridViewTextBoxColumn = new DataGridViewFilterTextBoxColumn();
            this.makerFIODataGridViewTextBoxColumn = new DataGridViewTextBoxColumn();
            this.otherInstructionDataGridViewTextBoxColumn = new DataGridViewTextBoxColumn();
            this.outputFIODataGridViewTextBoxColumn = new DataGridViewFilterTextBoxColumn();
            this.dateCloseDgvColumn = new DataGridViewTextBoxColumn();
            this.closeFIODataGridViewTextBoxColumn = new DataGridViewFilterTextBoxColumn();
            this.beginResDgvColumn = new DataGridViewTextBoxColumn();
            this.EndResDgvColumn = new DataGridViewTextBoxColumn();
            this.idDgvColumn = new DataGridViewTextBoxColumn();
            this.bsOrder = new BindingSource(this.components);
            this.dataSetOrder = new DataSet.DataSetOrder();
            this.toolStripOrder = new ToolStrip();
            this.toolBtnAddOrder = new ToolStripButton();
            this.toolBtnAddOrderDivision = new ToolStripDropDownButton();
            this.toolBtnEditOrder = new ToolStripButton();
            this.toolBtnReadOrder = new ToolStripButton();
            this.toolBtnDelOrder = new ToolStripButton();
            this.toolStripSeparator2 = new ToolStripSeparator();
            this.toolBtnRefresh = new ToolStripButton();
            this.toolStripSeparator1 = new ToolStripSeparator();
            this.toolBtnReport = new ToolStripButton();
            this.toolBtnReportExcel = new ToolStripButton();
            this.toolStripSeparator3 = new ToolStripSeparator();
            this.toolBtnOrderClose = new ToolStripButton();
            this.panelFilter = new Panel();
            this.checkBoxCloseOrder = new CheckBox();
            this.checkBoxCurrentOrder = new CheckBox();
            this.checkBoxRegistered = new CheckBox();
            this.checkBoxNoRegistered = new CheckBox();
            this.panelDateFilter = new Panel();
            this.panelTree = new Panel();
            this.splitContainerFilter = new SplitContainer();
            this.checkBoxWhereSub = new CheckBox();
            this.treeViewSchmObjects = new TreeViewSchmObjects();
            this.checkedListBoxDivision = new CheckedListBox();
            this.label3 = new Label();
            this.toolStripFilter = new ToolStrip();
            this.toolBtnFilter = new ToolStripButton();
            this.toolBtnFilterClear = new ToolStripButton();
            this.toolBtnFind = new ToolStripButton();
            this.toolTextBoxFind = new ToolStripTextBox();
            this.toolBtnFindPrev = new ToolStripButton();
            this.toolBtnFindNext = new ToolStripButton();
            this.dateTimePickerEnd = new DateTimePicker();
            this.label2 = new Label();
            this.dateTimePickerBegin = new DateTimePicker();
            this.label1 = new Label();
            this.tabControlOrder = new TabControl();
            this.tabPageView = new TabPage();
            this.tabPageEvents = new TabPage();
            this.dgvEvents = new DataGridViewExcelFilter();
            this.numDataGridViewTextBoxColumn = new DataGridViewFilterTextBoxColumn();
            this.srNumDgvColumn = new DataGridViewFilterTextBoxColumn();
            this.instructionDataGridViewTextBoxColumn1 = new DataGridViewFilterTextBoxColumn();
            this.acceptFIODataGridViewTextBoxColumn1 = new DataGridViewFilterTextBoxColumn();
            this.makerFioDataGridViewTextBoxColumn1 = new DataGridViewFilterTextBoxColumn();
            this.evntDataGridViewTextBoxColumn = new DataGridViewFilterTextBoxColumn();
            this.evntDateDataGridViewTextBoxColumn = new DataGridViewTextBoxColumn();
            this.dispDataGridViewTextBoxColumn = new DataGridViewFilterTextBoxColumn();
            this.closedDgvColumn = new DataGridViewTextBoxColumn();
            this.idDgvColumnEvent = new DataGridViewTextBoxColumn();
            this.bsOrderEvents = new BindingSource(this.components);
            this.splitContainer1 = new SplitContainer();
            this.dataGridViewFilterTextBoxColumn1 = new DataGridViewFilterTextBoxColumn();
            this.dataGridViewTextBoxColumn1 = new DataGridViewTextBoxColumn();
            this.dataGridViewFilterTextBoxColumn2 = new DataGridViewFilterTextBoxColumn();
            this.dataGridViewFilterTextBoxColumn3 = new DataGridViewFilterTextBoxColumn();
            this.dataGridViewTextBoxColumn2 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn3 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn4 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn5 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn6 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn7 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn8 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn9 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn10 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn11 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn12 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn13 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn14 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn15 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn16 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn17 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn18 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn19 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn20 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn21 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn22 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn23 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn24 = new DataGridViewTextBoxColumn();
            this.dataGridViewFilterTextBoxColumn4 = new DataGridViewFilterTextBoxColumn();
            this.dataGridViewFilterTextBoxColumn5 = new DataGridViewFilterTextBoxColumn();
            this.dataGridViewFilterTextBoxColumn6 = new DataGridViewFilterTextBoxColumn();
            this.dataGridViewFilterTextBoxColumn7 = new DataGridViewFilterTextBoxColumn();
            this.dataGridViewFilterTextBoxColumn8 = new DataGridViewFilterTextBoxColumn();
            this.dataGridViewTextBoxColumn25 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn26 = new DataGridViewTextBoxColumn();
            this.dataGridViewFilterTextBoxColumn9 = new DataGridViewFilterTextBoxColumn();
            ((ISupportInitialize)this.dgvOrder).BeginInit();
            ((ISupportInitialize)this.bsOrder).BeginInit();
            ((ISupportInitialize)this.dataSetOrder).BeginInit();
            this.toolStripOrder.SuspendLayout();
            this.panelFilter.SuspendLayout();
            this.panelDateFilter.SuspendLayout();
            this.panelTree.SuspendLayout();
            this.splitContainerFilter.Panel1.SuspendLayout();
            this.splitContainerFilter.Panel2.SuspendLayout();
            this.splitContainerFilter.SuspendLayout();
            this.toolStripFilter.SuspendLayout();
            this.tabControlOrder.SuspendLayout();
            this.tabPageView.SuspendLayout();
            this.tabPageEvents.SuspendLayout();
            ((ISupportInitialize)this.dgvEvents).BeginInit();
            ((ISupportInitialize)this.bsOrderEvents).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            base.SuspendLayout();
            this.dgvOrder.AllowUserToAddRows = false;
            this.dgvOrder.AllowUserToDeleteRows = false;
            this.dgvOrder.AutoGenerateColumns = false;
            dataGridViewCellStyle.Alignment = DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle.BackColor = SystemColors.Control;
            dataGridViewCellStyle.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 204);
            dataGridViewCellStyle.ForeColor = SystemColors.WindowText;
            dataGridViewCellStyle.SelectionBackColor = SystemColors.Highlight;
            dataGridViewCellStyle.SelectionForeColor = SystemColors.HighlightText;
            dataGridViewCellStyle.WrapMode = DataGridViewTriState.True;
            this.dgvOrder.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle;
            this.dgvOrder.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvOrder.Columns.AddRange(new DataGridViewColumn[]
            {
                this.numDgvColumn,
                this.srNumDataGridViewTextBoxColumn,
                this.dateOutputDataGridViewTextBoxColumn,
                this.dateBeginDataGridViewTextBoxColumn,
                this.dateEndDataGridViewTextBoxColumn,
                this.registeredDgvColumn,
                this.outputMakerDataGridViewTextBoxColumn,
                this.instructionDataGridViewTextBoxColumn,
                this.resolutionDataGridViewTextBoxColumn,
                this.srNameDataGridViewTextBoxColumn,
                this.headFioDataGridViewTextBoxColumn,
                this.acceptFIODataGridViewTextBoxColumn,
                this.watchFIODataGridViewTextBoxColumn,
                this.makerFIODataGridViewTextBoxColumn,
                this.otherInstructionDataGridViewTextBoxColumn,
                this.outputFIODataGridViewTextBoxColumn,
                this.dateCloseDgvColumn,
                this.closeFIODataGridViewTextBoxColumn,
                this.beginResDgvColumn,
                this.EndResDgvColumn,
                this.idDgvColumn
            });
            this.dgvOrder.DataSource = this.bsOrder;
            this.dgvOrder.Dock = DockStyle.Fill;
            this.dgvOrder.Location = new Point(3, 47);
            this.dgvOrder.Name = "dgvOrder";
            this.dgvOrder.ReadOnly = true;
            this.dgvOrder.RowHeadersWidth = 21;
            this.dgvOrder.RowTemplate.Height = 44;
            this.dgvOrder.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvOrder.Size = new Size(718, 487);
            this.dgvOrder.TabIndex = 0;
            this.dgvOrder.CellDoubleClick += new DataGridViewCellEventHandler( this.dgvOrder_CellDoubleClick);
            this.dgvOrder.CellFormatting += new DataGridViewCellFormattingEventHandler(this.dgvOrder_CellFormatting);
            this.numDgvColumn.DataPropertyName = "num";
            this.numDgvColumn.HeaderText = "№";
            this.numDgvColumn.Name = "numDgvColumn";
            this.numDgvColumn.ReadOnly = true;
            this.numDgvColumn.Resizable = DataGridViewTriState.True;
            this.numDgvColumn.Width = 50;
            this.srNumDataGridViewTextBoxColumn.DataPropertyName = "srNum";
            dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleCenter;
            this.srNumDataGridViewTextBoxColumn.DefaultCellStyle = dataGridViewCellStyle2;
            this.srNumDataGridViewTextBoxColumn.HeaderText = "Сетевой район";
            this.srNumDataGridViewTextBoxColumn.Name = "srNumDataGridViewTextBoxColumn";
            this.srNumDataGridViewTextBoxColumn.ReadOnly = true;
            this.srNumDataGridViewTextBoxColumn.Width = 80;
            this.dateOutputDataGridViewTextBoxColumn.DataPropertyName = "dateOutput";
            dataGridViewCellStyle3.Format = "dd.MM.yyyy HH:mm:ss";
            this.dateOutputDataGridViewTextBoxColumn.DefaultCellStyle = dataGridViewCellStyle3;
            this.dateOutputDataGridViewTextBoxColumn.HeaderText = "Дата выдачи наряда";
            this.dateOutputDataGridViewTextBoxColumn.Name = "dateOutputDataGridViewTextBoxColumn";
            this.dateOutputDataGridViewTextBoxColumn.ReadOnly = true;
            this.dateOutputDataGridViewTextBoxColumn.SortMode = DataGridViewColumnSortMode.Automatic;
            this.dateOutputDataGridViewTextBoxColumn.Width = 125;
            this.dateBeginDataGridViewTextBoxColumn.DataPropertyName = "dateBegin";
            this.dateBeginDataGridViewTextBoxColumn.HeaderText = "Дата начала работ";
            this.dateBeginDataGridViewTextBoxColumn.Name = "dateBeginDataGridViewTextBoxColumn";
            this.dateBeginDataGridViewTextBoxColumn.ReadOnly = true;
            this.dateBeginDataGridViewTextBoxColumn.Resizable = DataGridViewTriState.True;
            this.dateBeginDataGridViewTextBoxColumn.SortMode = DataGridViewColumnSortMode.Automatic;
            this.dateBeginDataGridViewTextBoxColumn.Width = 80;
            this.dateEndDataGridViewTextBoxColumn.DataPropertyName = "dateEnd";
            this.dateEndDataGridViewTextBoxColumn.HeaderText = "Дата окончания работ";
            this.dateEndDataGridViewTextBoxColumn.Name = "dateEndDataGridViewTextBoxColumn";
            this.dateEndDataGridViewTextBoxColumn.ReadOnly = true;
            this.dateEndDataGridViewTextBoxColumn.Resizable = DataGridViewTriState.True;
            this.dateEndDataGridViewTextBoxColumn.SortMode = DataGridViewColumnSortMode.Automatic;
            this.dateEndDataGridViewTextBoxColumn.Width = 80;
            this.registeredDgvColumn.DataPropertyName = "registered";
            this.registeredDgvColumn.HeaderText = "Зарегистрирован";
            this.registeredDgvColumn.Name = "registeredDgvColumn";
            this.registeredDgvColumn.ReadOnly = true;
            this.registeredDgvColumn.Resizable = DataGridViewTriState.True;
            this.registeredDgvColumn.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.registeredDgvColumn.Visible = false;
            this.outputMakerDataGridViewTextBoxColumn.DataPropertyName = "OutputMaker";
            dataGridViewCellStyle4.WrapMode = DataGridViewTriState.True;
            this.outputMakerDataGridViewTextBoxColumn.DefaultCellStyle = dataGridViewCellStyle4;
            this.outputMakerDataGridViewTextBoxColumn.HeaderText = "Наряд выдал Производитель работ";
            this.outputMakerDataGridViewTextBoxColumn.Name = "outputMakerDataGridViewTextBoxColumn";
            this.outputMakerDataGridViewTextBoxColumn.ReadOnly = true;
            this.instructionDataGridViewTextBoxColumn.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.instructionDataGridViewTextBoxColumn.DataPropertyName = "instruction";
            dataGridViewCellStyle5.WrapMode = DataGridViewTriState.True;
            this.instructionDataGridViewTextBoxColumn.DefaultCellStyle = dataGridViewCellStyle5;
            this.instructionDataGridViewTextBoxColumn.HeaderText = "Содержание работ";
            this.instructionDataGridViewTextBoxColumn.Name = "instructionDataGridViewTextBoxColumn";
            this.instructionDataGridViewTextBoxColumn.ReadOnly = true;
            this.instructionDataGridViewTextBoxColumn.Resizable = DataGridViewTriState.True;
            this.resolutionDataGridViewTextBoxColumn.DataPropertyName = "Resolution";
            dataGridViewCellStyle6.WrapMode = DataGridViewTriState.True;
            this.resolutionDataGridViewTextBoxColumn.DefaultCellStyle = dataGridViewCellStyle6;
            this.resolutionDataGridViewTextBoxColumn.HeaderText = "Разрешение выдал";
            this.resolutionDataGridViewTextBoxColumn.Name = "resolutionDataGridViewTextBoxColumn";
            this.resolutionDataGridViewTextBoxColumn.ReadOnly = true;
            this.resolutionDataGridViewTextBoxColumn.Width = 120;
            this.srNameDataGridViewTextBoxColumn.DataPropertyName = "srName";
            this.srNameDataGridViewTextBoxColumn.HeaderText = "Сетевой район (имя)";
            this.srNameDataGridViewTextBoxColumn.Name = "srNameDataGridViewTextBoxColumn";
            this.srNameDataGridViewTextBoxColumn.ReadOnly = true;
            this.srNameDataGridViewTextBoxColumn.Resizable = DataGridViewTriState.True;
            this.srNameDataGridViewTextBoxColumn.Visible = false;
            this.headFioDataGridViewTextBoxColumn.DataPropertyName = "headFio";
            this.headFioDataGridViewTextBoxColumn.HeaderText = "Руководитель работ";
            this.headFioDataGridViewTextBoxColumn.Name = "headFioDataGridViewTextBoxColumn";
            this.headFioDataGridViewTextBoxColumn.ReadOnly = true;
            this.headFioDataGridViewTextBoxColumn.Resizable = DataGridViewTriState.True;
            this.headFioDataGridViewTextBoxColumn.Visible = false;
            this.acceptFIODataGridViewTextBoxColumn.DataPropertyName = "acceptFIO";
            this.acceptFIODataGridViewTextBoxColumn.HeaderText = "Допускайщий";
            this.acceptFIODataGridViewTextBoxColumn.Name = "acceptFIODataGridViewTextBoxColumn";
            this.acceptFIODataGridViewTextBoxColumn.ReadOnly = true;
            this.acceptFIODataGridViewTextBoxColumn.Resizable = DataGridViewTriState.True;
            this.acceptFIODataGridViewTextBoxColumn.Visible = false;
            this.watchFIODataGridViewTextBoxColumn.DataPropertyName = "watchFIO";
            this.watchFIODataGridViewTextBoxColumn.HeaderText = "Наблюдающий";
            this.watchFIODataGridViewTextBoxColumn.Name = "watchFIODataGridViewTextBoxColumn";
            this.watchFIODataGridViewTextBoxColumn.ReadOnly = true;
            this.watchFIODataGridViewTextBoxColumn.Resizable = DataGridViewTriState.True;
            this.watchFIODataGridViewTextBoxColumn.Visible = false;
            this.makerFIODataGridViewTextBoxColumn.DataPropertyName = "makerFIO";
            this.makerFIODataGridViewTextBoxColumn.HeaderText = "Произовдитель работ";
            this.makerFIODataGridViewTextBoxColumn.Name = "makerFIODataGridViewTextBoxColumn";
            this.makerFIODataGridViewTextBoxColumn.ReadOnly = true;
            this.makerFIODataGridViewTextBoxColumn.Visible = false;
            this.otherInstructionDataGridViewTextBoxColumn.DataPropertyName = "otherInstruction";
            this.otherInstructionDataGridViewTextBoxColumn.HeaderText = "Отдельные указания";
            this.otherInstructionDataGridViewTextBoxColumn.Name = "otherInstructionDataGridViewTextBoxColumn";
            this.otherInstructionDataGridViewTextBoxColumn.ReadOnly = true;
            this.otherInstructionDataGridViewTextBoxColumn.Visible = false;
            this.outputFIODataGridViewTextBoxColumn.DataPropertyName = "outputFIO";
            this.outputFIODataGridViewTextBoxColumn.HeaderText = "Наряд выдал";
            this.outputFIODataGridViewTextBoxColumn.Name = "outputFIODataGridViewTextBoxColumn";
            this.outputFIODataGridViewTextBoxColumn.ReadOnly = true;
            this.outputFIODataGridViewTextBoxColumn.Resizable = DataGridViewTriState.True;
            this.outputFIODataGridViewTextBoxColumn.Visible = false;
            this.dateCloseDgvColumn.DataPropertyName = "dateClose";
            this.dateCloseDgvColumn.HeaderText = "Дата закрытия";
            this.dateCloseDgvColumn.Name = "dateCloseDgvColumn";
            this.dateCloseDgvColumn.ReadOnly = true;
            this.dateCloseDgvColumn.Visible = false;
            this.closeFIODataGridViewTextBoxColumn.DataPropertyName = "closeFIO";
            this.closeFIODataGridViewTextBoxColumn.HeaderText = "Закрыл наряд";
            this.closeFIODataGridViewTextBoxColumn.Name = "closeFIODataGridViewTextBoxColumn";
            this.closeFIODataGridViewTextBoxColumn.ReadOnly = true;
            this.closeFIODataGridViewTextBoxColumn.Resizable = DataGridViewTriState.True;
            this.closeFIODataGridViewTextBoxColumn.Visible = false;
            this.beginResDgvColumn.DataPropertyName = "beginRes";
            this.beginResDgvColumn.HeaderText = "beginRes";
            this.beginResDgvColumn.Name = "beginResDgvColumn";
            this.beginResDgvColumn.ReadOnly = true;
            this.beginResDgvColumn.Visible = false;
            this.EndResDgvColumn.DataPropertyName = "EndRes";
            this.EndResDgvColumn.HeaderText = "EndRes";
            this.EndResDgvColumn.Name = "EndResDgvColumn";
            this.EndResDgvColumn.ReadOnly = true;
            this.EndResDgvColumn.Visible = false;
            this.idDgvColumn.DataPropertyName = "id";
            this.idDgvColumn.HeaderText = "id";
            this.idDgvColumn.Name = "idDgvColumn";
            this.idDgvColumn.ReadOnly = true;
            this.idDgvColumn.Visible = false;
            this.bsOrder.DataMember = "vJ_Order";
            this.bsOrder.DataSource = this.dataSetOrder;
            this.dataSetOrder.DataSetName = "DataSetOrder";
            this.dataSetOrder.SchemaSerializationMode = SchemaSerializationMode.IncludeSchema;
            this.toolStripOrder.Items.AddRange(new ToolStripItem[]
            {
                this.toolBtnAddOrder,
                this.toolBtnAddOrderDivision,
                this.toolBtnEditOrder,
                this.toolBtnReadOrder,
                this.toolBtnDelOrder,
                this.toolStripSeparator2,
                this.toolBtnRefresh,
                this.toolStripSeparator1,
                this.toolBtnReport,
                this.toolBtnReportExcel,
                this.toolStripSeparator3,
                this.toolBtnOrderClose
            });
            this.toolStripOrder.Location = new Point(0, 0);
            this.toolStripOrder.Name = "toolStripOrder";
            this.toolStripOrder.Size = new Size(918, 25);
            this.toolStripOrder.TabIndex = 2;
            this.toolStripOrder.Text = "toolStrip1";
            this.toolBtnAddOrder.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnAddOrder.Image = Properties.Resources.ElementAdd;
            this.toolBtnAddOrder.ImageTransparentColor = Color.Magenta;
            this.toolBtnAddOrder.Name = "toolBtnAddOrder";
            this.toolBtnAddOrder.Size = new Size(23, 22);
            this.toolBtnAddOrder.Text = "Создать наряд";
            this.toolBtnAddOrder.Click +=new System.EventHandler( this.toolBtnAddOrder_Click);
            this.toolBtnAddOrderDivision.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnAddOrderDivision.Image = Properties.Resources.ElementAdd;
            this.toolBtnAddOrderDivision.ImageTransparentColor = Color.Magenta;
            this.toolBtnAddOrderDivision.Name = "toolBtnAddOrderDivision";
            this.toolBtnAddOrderDivision.Size = new Size(29, 22);
            this.toolBtnAddOrderDivision.Text = "Создать наряд";
            this.toolBtnEditOrder.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnEditOrder.Image = Properties.Resources.ElementEdit;
            this.toolBtnEditOrder.ImageTransparentColor = Color.Magenta;
            this.toolBtnEditOrder.Name = "toolBtnEditOrder";
            this.toolBtnEditOrder.Size = new Size(23, 22);
            this.toolBtnEditOrder.Text = "Редактировать";
            this.toolBtnEditOrder.Click += new System.EventHandler(this.toolBtnEditOrder_Click);
            this.toolBtnReadOrder.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnReadOrder.Image = Properties.Resources.ElementInformation1;
            this.toolBtnReadOrder.ImageTransparentColor = Color.Magenta;
            this.toolBtnReadOrder.Name = "toolBtnReadOrder";
            this.toolBtnReadOrder.Size = new Size(23, 22);
            this.toolBtnReadOrder.Text = "Просмотр наряда";
            this.toolBtnReadOrder.Click += new System.EventHandler(this.toolBtnReadOrder_Click);
            this.toolBtnDelOrder.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnDelOrder.Image = Properties.Resources.ElementDel;
            this.toolBtnDelOrder.ImageTransparentColor = Color.Magenta;
            this.toolBtnDelOrder.Name = "toolBtnDelOrder";
            this.toolBtnDelOrder.Size = new Size(23, 22);
            this.toolBtnDelOrder.Text = "Удалить наряд(ы)";
            this.toolBtnDelOrder.Click += new System.EventHandler(this.toolBtnDelOrder_Click);
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new Size(6, 25);
            this.toolBtnRefresh.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnRefresh.Image = Properties.Resources.refresh_16;
            this.toolBtnRefresh.ImageTransparentColor = Color.Magenta;
            this.toolBtnRefresh.Name = "toolBtnRefresh";
            this.toolBtnRefresh.Size = new Size(23, 22);
            this.toolBtnRefresh.Text = "Обновить";
            this.toolBtnRefresh.Click += new System.EventHandler(this.toolBtnRefresh_Click);
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new Size(6, 25);
            this.toolBtnReport.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnReport.Image = (Image)resources.GetObject("toolBtnReport.Image");
            this.toolBtnReport.ImageTransparentColor = Color.Magenta;
            this.toolBtnReport.Name = "toolBtnReport";
            this.toolBtnReport.Size = new Size(23, 22);
            this.toolBtnReport.Text = "toolStripButton1";
            this.toolBtnReport.Visible = false;
            this.toolBtnReport.Click += new System.EventHandler( this.toolBtnReport_Click);
            this.toolBtnReportExcel.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnReportExcel.Image = Properties.Resources.microsoftoffice2007excel_7581;
            this.toolBtnReportExcel.ImageTransparentColor = Color.Magenta;
            this.toolBtnReportExcel.Name = "toolBtnReportExcel";
            this.toolBtnReportExcel.Size = new Size(23, 22);
            this.toolBtnReportExcel.Text = "Печать наряда";
            this.toolBtnReportExcel.Click += new System.EventHandler(this.toolBtnReportExcel_Click);
            this.toolStripSeparator3.Name = "toolStripSeparator3";
            this.toolStripSeparator3.Size = new Size(6, 25);
            this.toolBtnOrderClose.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnOrderClose.Image = Properties.Resources.Orderclose;
            this.toolBtnOrderClose.ImageTransparentColor = Color.Transparent;
            this.toolBtnOrderClose.Name = "toolBtnOrderClose";
            this.toolBtnOrderClose.Size = new Size(23, 22);
            this.toolBtnOrderClose.Text = "Закрыть наряды";
            this.toolBtnOrderClose.Click += new System.EventHandler(this.toolBtnOrderClose_Click);
            this.panelFilter.Controls.Add(this.checkBoxCloseOrder);
            this.panelFilter.Controls.Add(this.checkBoxCurrentOrder);
            this.panelFilter.Controls.Add(this.checkBoxRegistered);
            this.panelFilter.Controls.Add(this.checkBoxNoRegistered);
            this.panelFilter.Dock = DockStyle.Top;
            this.panelFilter.Location = new Point(3, 3);
            this.panelFilter.Name = "panelFilter";
            this.panelFilter.Size = new Size(718, 44);
            this.panelFilter.TabIndex = 3;
            this.checkBoxCloseOrder.AutoSize = true;
            this.checkBoxCloseOrder.BackColor = Color.Gray;
            this.checkBoxCloseOrder.Checked = true;
            this.checkBoxCloseOrder.CheckState = CheckState.Checked;
            this.checkBoxCloseOrder.Location = new Point(411, 9);
            this.checkBoxCloseOrder.Name = "checkBoxCloseOrder";
            this.checkBoxCloseOrder.Size = new Size(78, 17);
            this.checkBoxCloseOrder.TabIndex = 3;
            this.checkBoxCloseOrder.Text = "Закрытые";
            this.checkBoxCloseOrder.UseVisualStyleBackColor = false;
            this.checkBoxCloseOrder.CheckedChanged += new System.EventHandler( this.checkBoxRegistered_CheckedChanged);
            this.checkBoxCurrentOrder.AutoSize = true;
            this.checkBoxCurrentOrder.BackColor = Color.LawnGreen;
            this.checkBoxCurrentOrder.Checked = true;
            this.checkBoxCurrentOrder.CheckState = CheckState.Checked;
            this.checkBoxCurrentOrder.Location = new Point(307, 9);
            this.checkBoxCurrentOrder.Name = "checkBoxCurrentOrder";
            this.checkBoxCurrentOrder.Size = new Size(98, 17);
            this.checkBoxCurrentOrder.TabIndex = 2;
            this.checkBoxCurrentOrder.Text = "Действующие";
            this.checkBoxCurrentOrder.UseVisualStyleBackColor = false;
            this.checkBoxCurrentOrder.CheckedChanged += new System.EventHandler( this.checkBoxRegistered_CheckedChanged);
            this.checkBoxRegistered.AutoSize = true;
            this.checkBoxRegistered.BackColor = Color.White;
            this.checkBoxRegistered.Checked = true;
            this.checkBoxRegistered.CheckState = CheckState.Checked;
            this.checkBoxRegistered.Location = new Point(166, 9);
            this.checkBoxRegistered.Name = "checkBoxRegistered";
            this.checkBoxRegistered.Size = new Size(135, 17);
            this.checkBoxRegistered.TabIndex = 1;
            this.checkBoxRegistered.Text = "Зарегистрированные";
            this.checkBoxRegistered.UseVisualStyleBackColor = false;
            this.checkBoxRegistered.CheckedChanged += new System.EventHandler(this.checkBoxRegistered_CheckedChanged);
            this.checkBoxNoRegistered.AutoSize = true;
            this.checkBoxNoRegistered.BackColor = Color.Yellow;
            this.checkBoxNoRegistered.Checked = true;
            this.checkBoxNoRegistered.CheckState = CheckState.Checked;
            this.checkBoxNoRegistered.Location = new Point(12, 9);
            this.checkBoxNoRegistered.Name = "checkBoxNoRegistered";
            this.checkBoxNoRegistered.Size = new Size(148, 17);
            this.checkBoxNoRegistered.TabIndex = 0;
            this.checkBoxNoRegistered.Text = "Незарегистрированные";
            this.checkBoxNoRegistered.UseVisualStyleBackColor = false;
            this.checkBoxNoRegistered.CheckedChanged += new System.EventHandler(this.checkBoxRegistered_CheckedChanged);
            this.panelDateFilter.Controls.Add(this.panelTree);
            this.panelDateFilter.Controls.Add(this.toolStripFilter);
            this.panelDateFilter.Controls.Add(this.dateTimePickerEnd);
            this.panelDateFilter.Controls.Add(this.label2);
            this.panelDateFilter.Controls.Add(this.dateTimePickerBegin);
            this.panelDateFilter.Controls.Add(this.label1);
            this.panelDateFilter.Dock = DockStyle.Fill;
            this.panelDateFilter.Location = new Point(0, 0);
            this.panelDateFilter.Name = "panelDateFilter";
            this.panelDateFilter.Size = new Size(182, 563);
            this.panelDateFilter.TabIndex = 4;
            this.panelTree.Anchor = (AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right);
            this.panelTree.Controls.Add(this.splitContainerFilter);
            this.panelTree.Location = new Point(0, 106);
            this.panelTree.Name = "panelTree";
            this.panelTree.Size = new Size(182, 457);
            this.panelTree.TabIndex = 10;
            this.splitContainerFilter.Dock = DockStyle.Fill;
            this.splitContainerFilter.FixedPanel = FixedPanel.Panel2;
            this.splitContainerFilter.Location = new Point(0, 0);
            this.splitContainerFilter.Name = "splitContainerFilter";
            this.splitContainerFilter.Orientation = Orientation.Horizontal;
            this.splitContainerFilter.Panel1.Controls.Add(this.checkBoxWhereSub);
            this.splitContainerFilter.Panel1.Controls.Add(this.treeViewSchmObjects);
            this.splitContainerFilter.Panel2.Controls.Add(this.checkedListBoxDivision);
            this.splitContainerFilter.Panel2.Controls.Add(this.label3);
            this.splitContainerFilter.Size = new Size(182, 457);
            this.splitContainerFilter.SplitterDistance = 352;
            this.splitContainerFilter.TabIndex = 10;
            this.checkBoxWhereSub.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
            this.checkBoxWhereSub.AutoSize = true;
            this.checkBoxWhereSub.Checked = true;
            this.checkBoxWhereSub.CheckState = CheckState.Checked;
            this.checkBoxWhereSub.Location = new Point(6, 333);
            this.checkBoxWhereSub.Name = "checkBoxWhereSub";
            this.checkBoxWhereSub.Size = new Size(180, 17);
            this.checkBoxWhereSub.TabIndex = 13;
            this.checkBoxWhereSub.Text = "Фильтровать по подстанциям";
            this.checkBoxWhereSub.UseVisualStyleBackColor = true;
            this.treeViewSchmObjects.Anchor = (AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right);
            this.treeViewSchmObjects.CheckBoxes = true;
            this.treeViewSchmObjects.Location = new Point(0, 0);
            this.treeViewSchmObjects.Name = "treeViewSchmObjects";
            this.treeViewSchmObjects.Size = new Size(182, 327);
            this.treeViewSchmObjects.SqlSettings = null;
            this.treeViewSchmObjects.TabIndex = 9;
            this.checkedListBoxDivision.Dock = DockStyle.Fill;
            this.checkedListBoxDivision.FormattingEnabled = true;
            this.checkedListBoxDivision.Location = new Point(0, 13);
            this.checkedListBoxDivision.Name = "checkedListBoxDivision";
            this.checkedListBoxDivision.Size = new Size(182, 88);
            this.checkedListBoxDivision.TabIndex = 1;
            this.label3.AutoSize = true;
            this.label3.Dock = DockStyle.Top;
            this.label3.Location = new Point(0, 0);
            this.label3.Name = "label3";
            this.label3.Size = new Size(87, 13);
            this.label3.TabIndex = 0;
            this.label3.Text = "Подразделения";
            this.toolStripFilter.Items.AddRange(new ToolStripItem[]
            {
                this.toolBtnFilter,
                this.toolBtnFilterClear,
                this.toolBtnFind,
                this.toolTextBoxFind,
                this.toolBtnFindPrev,
                this.toolBtnFindNext
            });
            this.toolStripFilter.Location = new Point(0, 0);
            this.toolStripFilter.Name = "toolStripFilter";
            this.toolStripFilter.Size = new Size(182, 25);
            this.toolStripFilter.TabIndex = 10;
            this.toolStripFilter.Text = "toolStrip1";
            this.toolBtnFilter.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnFilter.Image = Properties.Resources.filter;
            this.toolBtnFilter.ImageTransparentColor = Color.Transparent;
            this.toolBtnFilter.Name = "toolBtnFilter";
            this.toolBtnFilter.Size = new Size(23, 22);
            this.toolBtnFilter.Text = "Применить фильтр";
            this.toolBtnFilter.Click += new System.EventHandler(this.toolBtnFilter_Click);
            this.toolBtnFilterClear.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnFilterClear.Image = Properties.Resources.filter_delete;
            this.toolBtnFilterClear.ImageTransparentColor = Color.Magenta;
            this.toolBtnFilterClear.Name = "toolBtnFilterClear";
            this.toolBtnFilterClear.Size = new Size(23, 22);
            this.toolBtnFilterClear.Text = "Отменить фильтр";
            this.toolBtnFilterClear.Click += new System.EventHandler(this.toolBtnFilterClear_Click);
            this.toolBtnFind.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnFind.Image = Properties.Resources.Find;
            this.toolBtnFind.ImageTransparentColor = Color.Magenta;
            this.toolBtnFind.Name = "toolBtnFind";
            this.toolBtnFind.Size = new Size(23, 22);
            this.toolBtnFind.Text = "Поиск";
            this.toolBtnFind.Click += new System.EventHandler(this.toolBtnFind_Click);
            this.toolTextBoxFind.Name = "toolTextBoxFind";
            this.toolTextBoxFind.Size = new Size(54, 25);
            this.toolTextBoxFind.KeyDown += new KeyEventHandler(this.toolTextBoxFind_KeyDown);
            this.toolBtnFindPrev.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnFindPrev.Image = Properties.Resources.FindPrev;
            this.toolBtnFindPrev.ImageTransparentColor = Color.Magenta;
            this.toolBtnFindPrev.Name = "toolBtnFindPrev";
            this.toolBtnFindPrev.Size = new Size(23, 22);
            this.toolBtnFindPrev.Text = "Поиск назад";
            this.toolBtnFindPrev.Click += new System.EventHandler(this.toolBtnFindPrev_Click);
            this.toolBtnFindNext.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.toolBtnFindNext.Image = Properties.Resources.FindNext;
            this.toolBtnFindNext.ImageTransparentColor = Color.Magenta;
            this.toolBtnFindNext.Name = "toolBtnFindNext";
            this.toolBtnFindNext.Size = new Size(23, 22);
            this.toolBtnFindNext.Text = "Поиск вперед";
            this.toolBtnFindNext.Click += new System.EventHandler(this.toolBtnFindNext_Click);
            this.dateTimePickerEnd.Anchor = (AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right);
            this.dateTimePickerEnd.Location = new Point(6, 80);
            this.dateTimePickerEnd.Name = "dateTimePickerEnd";
            this.dateTimePickerEnd.Size = new Size(168, 20);
            this.dateTimePickerEnd.TabIndex = 7;
            this.dateTimePickerEnd.ValueChanged += new System.EventHandler( this.dateTimePickerEnd_ValueChanged);
            this.label2.AutoSize = true;
            this.label2.Location = new Point(3, 64);
            this.label2.Name = "label2";
            this.label2.Size = new Size(38, 13);
            this.label2.TabIndex = 6;
            this.label2.Text = "Конец";
            this.dateTimePickerBegin.Anchor = (AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right);
            this.dateTimePickerBegin.Location = new Point(6, 41);
            this.dateTimePickerBegin.Name = "dateTimePickerBegin";
            this.dateTimePickerBegin.Size = new Size(168, 20);
            this.dateTimePickerBegin.TabIndex = 5;
            this.dateTimePickerBegin.ValueChanged +=new System.EventHandler( this.dateTimePickerBegin_ValueChanged);
            this.label1.AutoSize = true;
            this.label1.Location = new Point(3, 25);
            this.label1.Name = "label1";
            this.label1.Size = new Size(44, 13);
            this.label1.TabIndex = 4;
            this.label1.Text = "Начало";
            this.tabControlOrder.Controls.Add(this.tabPageView);
            this.tabControlOrder.Controls.Add(this.tabPageEvents);
            this.tabControlOrder.Dock = DockStyle.Fill;
            this.tabControlOrder.Location = new Point(0, 0);
            this.tabControlOrder.Name = "tabControlOrder";
            this.tabControlOrder.SelectedIndex = 0;
            this.tabControlOrder.Size = new Size(732, 563);
            this.tabControlOrder.TabIndex = 5;
            this.tabControlOrder.SelectedIndexChanged +=new System.EventHandler( this.tabControlOrder_SelectedIndexChanged);
            this.tabPageView.Controls.Add(this.dgvOrder);
            this.tabPageView.Controls.Add(this.panelFilter);
            this.tabPageView.Location = new Point(4, 22);
            this.tabPageView.Name = "tabPageView";
            this.tabPageView.Padding = new Padding(3, 3, 3, 3);
            this.tabPageView.Size = new Size(724, 537);
            this.tabPageView.TabIndex = 0;
            this.tabPageView.Text = "Просмотр";
            this.tabPageView.UseVisualStyleBackColor = true;
            this.tabPageEvents.Controls.Add(this.dgvEvents);
            this.tabPageEvents.Location = new Point(4, 22);
            this.tabPageEvents.Name = "tabPageEvents";
            this.tabPageEvents.Padding = new Padding(3, 3, 3, 3);
            this.tabPageEvents.Size = new Size(770, 542);
            this.tabPageEvents.TabIndex = 1;
            this.tabPageEvents.Text = "События";
            this.tabPageEvents.UseVisualStyleBackColor = true;
            this.dgvEvents.AllowUserToAddRows = false;
            this.dgvEvents.AllowUserToDeleteRows = false;
            this.dgvEvents.AutoGenerateColumns = false;
            this.dgvEvents.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvEvents.Columns.AddRange(new DataGridViewColumn[]
            {
                this.numDataGridViewTextBoxColumn,
                this.srNumDgvColumn,
                this.instructionDataGridViewTextBoxColumn1,
                this.acceptFIODataGridViewTextBoxColumn1,
                this.makerFioDataGridViewTextBoxColumn1,
                this.evntDataGridViewTextBoxColumn,
                this.evntDateDataGridViewTextBoxColumn,
                this.dispDataGridViewTextBoxColumn,
                this.closedDgvColumn,
                this.idDgvColumnEvent
            });
            this.dgvEvents.DataSource = this.bsOrderEvents;
            this.dgvEvents.Dock = DockStyle.Fill;
            this.dgvEvents.Location = new Point(3, 3);
            this.dgvEvents.Name = "dgvEvents";
            this.dgvEvents.ReadOnly = true;
            this.dgvEvents.RowHeadersWidth = 21;
            this.dgvEvents.RowTemplate.Height = 44;
            this.dgvEvents.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvEvents.Size = new Size(764, 536);
            this.dgvEvents.TabIndex = 0;
            this.dgvEvents.CellDoubleClick += new DataGridViewCellEventHandler( this.dgvEvents_CellDoubleClick);
            this.dgvEvents.CellFormatting += new DataGridViewCellFormattingEventHandler (this.dgvEvents_CellFormatting);
            this.numDataGridViewTextBoxColumn.DataPropertyName = "num";
            this.numDataGridViewTextBoxColumn.HeaderText = "№ наряда";
            this.numDataGridViewTextBoxColumn.Name = "numDataGridViewTextBoxColumn";
            this.numDataGridViewTextBoxColumn.ReadOnly = true;
            this.numDataGridViewTextBoxColumn.Resizable = DataGridViewTriState.True;
            this.numDataGridViewTextBoxColumn.Width = 60;
            this.srNumDgvColumn.DataPropertyName = "srNum";
            this.srNumDgvColumn.HeaderText = "Сетевой район";
            this.srNumDgvColumn.Name = "srNumDgvColumn";
            this.srNumDgvColumn.ReadOnly = true;
            this.srNumDgvColumn.Width = 50;
            this.instructionDataGridViewTextBoxColumn1.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.instructionDataGridViewTextBoxColumn1.DataPropertyName = "instruction";
            this.instructionDataGridViewTextBoxColumn1.HeaderText = "Содержание работ";
            this.instructionDataGridViewTextBoxColumn1.Name = "instructionDataGridViewTextBoxColumn1";
            this.instructionDataGridViewTextBoxColumn1.ReadOnly = true;
            this.instructionDataGridViewTextBoxColumn1.Resizable = DataGridViewTriState.True;
            this.acceptFIODataGridViewTextBoxColumn1.DataPropertyName = "acceptFIO";
            this.acceptFIODataGridViewTextBoxColumn1.HeaderText = "Допускающий";
            this.acceptFIODataGridViewTextBoxColumn1.Name = "acceptFIODataGridViewTextBoxColumn1";
            this.acceptFIODataGridViewTextBoxColumn1.ReadOnly = true;
            this.acceptFIODataGridViewTextBoxColumn1.Resizable = DataGridViewTriState.True;
            this.makerFioDataGridViewTextBoxColumn1.DataPropertyName = "makerFio";
            this.makerFioDataGridViewTextBoxColumn1.HeaderText = "Производитель";
            this.makerFioDataGridViewTextBoxColumn1.Name = "makerFioDataGridViewTextBoxColumn1";
            this.makerFioDataGridViewTextBoxColumn1.ReadOnly = true;
            this.makerFioDataGridViewTextBoxColumn1.Resizable = DataGridViewTriState.True;
            this.evntDataGridViewTextBoxColumn.DataPropertyName = "Evnt";
            this.evntDataGridViewTextBoxColumn.HeaderText = "Состояние работ";
            this.evntDataGridViewTextBoxColumn.Name = "evntDataGridViewTextBoxColumn";
            this.evntDataGridViewTextBoxColumn.ReadOnly = true;
            this.evntDataGridViewTextBoxColumn.Resizable = DataGridViewTriState.True;
            this.evntDateDataGridViewTextBoxColumn.DataPropertyName = "EvntDate";
            this.evntDateDataGridViewTextBoxColumn.HeaderText = "Дата";
            this.evntDateDataGridViewTextBoxColumn.Name = "evntDateDataGridViewTextBoxColumn";
            this.evntDateDataGridViewTextBoxColumn.ReadOnly = true;
            this.dispDataGridViewTextBoxColumn.DataPropertyName = "disp";
            this.dispDataGridViewTextBoxColumn.HeaderText = "Диспетчер";
            this.dispDataGridViewTextBoxColumn.Name = "dispDataGridViewTextBoxColumn";
            this.dispDataGridViewTextBoxColumn.ReadOnly = true;
            this.dispDataGridViewTextBoxColumn.Resizable = DataGridViewTriState.True;
            this.closedDgvColumn.DataPropertyName = "closed";
            this.closedDgvColumn.HeaderText = "closed";
            this.closedDgvColumn.Name = "closedDgvColumn";
            this.closedDgvColumn.ReadOnly = true;
            this.closedDgvColumn.Visible = false;
            this.idDgvColumnEvent.DataPropertyName = "id";
            this.idDgvColumnEvent.HeaderText = "id";
            this.idDgvColumnEvent.Name = "idDgvColumnEvent";
            this.idDgvColumnEvent.ReadOnly = true;
            this.idDgvColumnEvent.Visible = false;
            this.bsOrderEvents.DataMember = "vJ_OrderEvents";
            this.bsOrderEvents.DataSource = this.dataSetOrder;
            this.splitContainer1.Dock = DockStyle.Fill;
            this.splitContainer1.FixedPanel = FixedPanel.Panel1;
            this.splitContainer1.Location = new Point(0, 25);
            this.splitContainer1.Name = "splitContainer1";
            this.splitContainer1.Panel1.Controls.Add(this.panelDateFilter);
            this.splitContainer1.Panel2.Controls.Add(this.tabControlOrder);
            this.splitContainer1.Size = new Size(918, 563);
            this.splitContainer1.SplitterDistance = 182;
            this.splitContainer1.TabIndex = 6;
            this.dataGridViewFilterTextBoxColumn1.DataPropertyName = "num";
            this.dataGridViewFilterTextBoxColumn1.HeaderText = "№";
            this.dataGridViewFilterTextBoxColumn1.Name = "dataGridViewFilterTextBoxColumn1";
            this.dataGridViewFilterTextBoxColumn1.ReadOnly = true;
            this.dataGridViewFilterTextBoxColumn1.Resizable = DataGridViewTriState.True;
            this.dataGridViewFilterTextBoxColumn1.Width = 50;
            this.dataGridViewTextBoxColumn1.DataPropertyName = "OutputMaker";
            dataGridViewCellStyle7.WrapMode = DataGridViewTriState.True;
            this.dataGridViewTextBoxColumn1.DefaultCellStyle = dataGridViewCellStyle7;
            this.dataGridViewTextBoxColumn1.HeaderText = "Наряд выдал Производитель работ";
            this.dataGridViewTextBoxColumn1.Name = "dataGridViewTextBoxColumn1";
            this.dataGridViewTextBoxColumn1.ReadOnly = true;
            this.dataGridViewTextBoxColumn1.Resizable = DataGridViewTriState.False;
            this.dataGridViewFilterTextBoxColumn2.DataPropertyName = "srNum";
            dataGridViewCellStyle8.Alignment = DataGridViewContentAlignment.MiddleCenter;
            this.dataGridViewFilterTextBoxColumn2.DefaultCellStyle = dataGridViewCellStyle8;
            this.dataGridViewFilterTextBoxColumn2.HeaderText = "Сетевой район";
            this.dataGridViewFilterTextBoxColumn2.Name = "dataGridViewFilterTextBoxColumn2";
            this.dataGridViewFilterTextBoxColumn2.ReadOnly = true;
            this.dataGridViewFilterTextBoxColumn2.Resizable = DataGridViewTriState.False;
            this.dataGridViewFilterTextBoxColumn2.Width = 80;
            this.dataGridViewFilterTextBoxColumn3.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.dataGridViewFilterTextBoxColumn3.DataPropertyName = "instruction";
            dataGridViewCellStyle9.WrapMode = DataGridViewTriState.True;
            this.dataGridViewFilterTextBoxColumn3.DefaultCellStyle = dataGridViewCellStyle9;
            this.dataGridViewFilterTextBoxColumn3.HeaderText = "Содержание работ";
            this.dataGridViewFilterTextBoxColumn3.Name = "dataGridViewFilterTextBoxColumn3";
            this.dataGridViewFilterTextBoxColumn3.ReadOnly = true;
            this.dataGridViewFilterTextBoxColumn3.Resizable = DataGridViewTriState.True;
            this.dataGridViewTextBoxColumn2.DataPropertyName = "Resolution";
            dataGridViewCellStyle10.WrapMode = DataGridViewTriState.True;
            this.dataGridViewTextBoxColumn2.DefaultCellStyle = dataGridViewCellStyle10;
            this.dataGridViewTextBoxColumn2.HeaderText = "Разрешение выдал";
            this.dataGridViewTextBoxColumn2.Name = "dataGridViewTextBoxColumn2";
            this.dataGridViewTextBoxColumn2.ReadOnly = true;
            this.dataGridViewTextBoxColumn2.Width = 120;
            this.dataGridViewTextBoxColumn3.DataPropertyName = "idSR";
            this.dataGridViewTextBoxColumn3.HeaderText = "idSR";
            this.dataGridViewTextBoxColumn3.Name = "dataGridViewTextBoxColumn3";
            this.dataGridViewTextBoxColumn3.ReadOnly = true;
            this.dataGridViewTextBoxColumn3.Visible = false;
            this.dataGridViewTextBoxColumn4.DataPropertyName = "srName";
            this.dataGridViewTextBoxColumn4.HeaderText = "srName";
            this.dataGridViewTextBoxColumn4.Name = "dataGridViewTextBoxColumn4";
            this.dataGridViewTextBoxColumn4.ReadOnly = true;
            this.dataGridViewTextBoxColumn4.Visible = false;
            this.dataGridViewTextBoxColumn5.DataPropertyName = "headworker";
            this.dataGridViewTextBoxColumn5.HeaderText = "headworker";
            this.dataGridViewTextBoxColumn5.Name = "dataGridViewTextBoxColumn5";
            this.dataGridViewTextBoxColumn5.ReadOnly = true;
            this.dataGridViewTextBoxColumn5.Visible = false;
            this.dataGridViewTextBoxColumn6.DataPropertyName = "headFio";
            this.dataGridViewTextBoxColumn6.HeaderText = "headFio";
            this.dataGridViewTextBoxColumn6.Name = "dataGridViewTextBoxColumn6";
            this.dataGridViewTextBoxColumn6.ReadOnly = true;
            this.dataGridViewTextBoxColumn6.Visible = false;
            this.dataGridViewTextBoxColumn7.DataPropertyName = "acceptworker";
            this.dataGridViewTextBoxColumn7.HeaderText = "acceptworker";
            this.dataGridViewTextBoxColumn7.Name = "dataGridViewTextBoxColumn7";
            this.dataGridViewTextBoxColumn7.ReadOnly = true;
            this.dataGridViewTextBoxColumn7.Visible = false;
            this.dataGridViewTextBoxColumn8.DataPropertyName = "acceptFIO";
            this.dataGridViewTextBoxColumn8.HeaderText = "acceptFIO";
            this.dataGridViewTextBoxColumn8.Name = "dataGridViewTextBoxColumn8";
            this.dataGridViewTextBoxColumn8.ReadOnly = true;
            this.dataGridViewTextBoxColumn8.Visible = false;
            this.dataGridViewTextBoxColumn9.DataPropertyName = "id";
            this.dataGridViewTextBoxColumn9.HeaderText = "id";
            this.dataGridViewTextBoxColumn9.Name = "dataGridViewTextBoxColumn9";
            this.dataGridViewTextBoxColumn9.ReadOnly = true;
            this.dataGridViewTextBoxColumn9.Visible = false;
            this.dataGridViewTextBoxColumn10.DataPropertyName = "watchWorker";
            this.dataGridViewTextBoxColumn10.HeaderText = "watchWorker";
            this.dataGridViewTextBoxColumn10.Name = "dataGridViewTextBoxColumn10";
            this.dataGridViewTextBoxColumn10.ReadOnly = true;
            this.dataGridViewTextBoxColumn10.Visible = false;
            this.dataGridViewTextBoxColumn11.DataPropertyName = "watchFIO";
            this.dataGridViewTextBoxColumn11.HeaderText = "watchFIO";
            this.dataGridViewTextBoxColumn11.Name = "dataGridViewTextBoxColumn11";
            this.dataGridViewTextBoxColumn11.ReadOnly = true;
            this.dataGridViewTextBoxColumn11.Visible = false;
            this.dataGridViewTextBoxColumn12.DataPropertyName = "makerWorker";
            this.dataGridViewTextBoxColumn12.HeaderText = "makerWorker";
            this.dataGridViewTextBoxColumn12.Name = "dataGridViewTextBoxColumn12";
            this.dataGridViewTextBoxColumn12.ReadOnly = true;
            this.dataGridViewTextBoxColumn12.Visible = false;
            this.dataGridViewTextBoxColumn13.DataPropertyName = "makerFIO";
            this.dataGridViewTextBoxColumn13.HeaderText = "makerFIO";
            this.dataGridViewTextBoxColumn13.Name = "dataGridViewTextBoxColumn13";
            this.dataGridViewTextBoxColumn13.ReadOnly = true;
            this.dataGridViewTextBoxColumn13.Visible = false;
            this.dataGridViewTextBoxColumn14.DataPropertyName = "otherInstruction";
            this.dataGridViewTextBoxColumn14.HeaderText = "otherInstruction";
            this.dataGridViewTextBoxColumn14.Name = "dataGridViewTextBoxColumn14";
            this.dataGridViewTextBoxColumn14.ReadOnly = true;
            this.dataGridViewTextBoxColumn14.Visible = false;
            this.dataGridViewTextBoxColumn15.DataPropertyName = "outputWorker";
            this.dataGridViewTextBoxColumn15.HeaderText = "outputWorker";
            this.dataGridViewTextBoxColumn15.Name = "dataGridViewTextBoxColumn15";
            this.dataGridViewTextBoxColumn15.ReadOnly = true;
            this.dataGridViewTextBoxColumn15.Visible = false;
            this.dataGridViewTextBoxColumn16.DataPropertyName = "outputFIO";
            this.dataGridViewTextBoxColumn16.HeaderText = "outputFIO";
            this.dataGridViewTextBoxColumn16.Name = "dataGridViewTextBoxColumn16";
            this.dataGridViewTextBoxColumn16.ReadOnly = true;
            this.dataGridViewTextBoxColumn16.Visible = false;
            this.dataGridViewTextBoxColumn17.DataPropertyName = "dateClose";
            this.dataGridViewTextBoxColumn17.HeaderText = "dateClose";
            this.dataGridViewTextBoxColumn17.Name = "dataGridViewTextBoxColumn17";
            this.dataGridViewTextBoxColumn17.ReadOnly = true;
            this.dataGridViewTextBoxColumn17.Visible = false;
            this.dataGridViewTextBoxColumn18.DataPropertyName = "closeWorker";
            this.dataGridViewTextBoxColumn18.HeaderText = "closeWorker";
            this.dataGridViewTextBoxColumn18.Name = "dataGridViewTextBoxColumn18";
            this.dataGridViewTextBoxColumn18.ReadOnly = true;
            this.dataGridViewTextBoxColumn18.Visible = false;
            this.dataGridViewTextBoxColumn19.DataPropertyName = "closeFIO";
            this.dataGridViewTextBoxColumn19.HeaderText = "closeFIO";
            this.dataGridViewTextBoxColumn19.Name = "dataGridViewTextBoxColumn19";
            this.dataGridViewTextBoxColumn19.ReadOnly = true;
            this.dataGridViewTextBoxColumn19.Visible = false;
            this.dataGridViewTextBoxColumn20.DataPropertyName = "beginRes";
            this.dataGridViewTextBoxColumn20.HeaderText = "beginRes";
            this.dataGridViewTextBoxColumn20.Name = "dataGridViewTextBoxColumn20";
            this.dataGridViewTextBoxColumn20.ReadOnly = true;
            this.dataGridViewTextBoxColumn20.Visible = false;
            this.dataGridViewTextBoxColumn21.DataPropertyName = "EndRes";
            this.dataGridViewTextBoxColumn21.HeaderText = "EndRes";
            this.dataGridViewTextBoxColumn21.Name = "dataGridViewTextBoxColumn21";
            this.dataGridViewTextBoxColumn21.ReadOnly = true;
            this.dataGridViewTextBoxColumn21.Visible = false;
            this.dataGridViewTextBoxColumn22.DataPropertyName = "resWorkerId";
            this.dataGridViewTextBoxColumn22.HeaderText = "resWorkerId";
            this.dataGridViewTextBoxColumn22.Name = "dataGridViewTextBoxColumn22";
            this.dataGridViewTextBoxColumn22.ReadOnly = true;
            this.dataGridViewTextBoxColumn22.Visible = false;
            this.dataGridViewTextBoxColumn23.DataPropertyName = "resWorker";
            this.dataGridViewTextBoxColumn23.HeaderText = "resWorker";
            this.dataGridViewTextBoxColumn23.Name = "dataGridViewTextBoxColumn23";
            this.dataGridViewTextBoxColumn23.ReadOnly = true;
            this.dataGridViewTextBoxColumn23.Visible = false;
            this.dataGridViewTextBoxColumn24.DataPropertyName = "id";
            this.dataGridViewTextBoxColumn24.HeaderText = "id";
            this.dataGridViewTextBoxColumn24.Name = "dataGridViewTextBoxColumn24";
            this.dataGridViewTextBoxColumn24.ReadOnly = true;
            this.dataGridViewTextBoxColumn24.Visible = false;
            this.dataGridViewFilterTextBoxColumn4.DataPropertyName = "num";
            this.dataGridViewFilterTextBoxColumn4.HeaderText = "№ наряда";
            this.dataGridViewFilterTextBoxColumn4.Name = "dataGridViewFilterTextBoxColumn4";
            this.dataGridViewFilterTextBoxColumn4.ReadOnly = true;
            this.dataGridViewFilterTextBoxColumn4.Resizable = DataGridViewTriState.True;
            this.dataGridViewFilterTextBoxColumn4.Width = 60;
            this.dataGridViewFilterTextBoxColumn5.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.dataGridViewFilterTextBoxColumn5.DataPropertyName = "instruction";
            this.dataGridViewFilterTextBoxColumn5.HeaderText = "Содержание работ";
            this.dataGridViewFilterTextBoxColumn5.Name = "dataGridViewFilterTextBoxColumn5";
            this.dataGridViewFilterTextBoxColumn5.ReadOnly = true;
            this.dataGridViewFilterTextBoxColumn5.Resizable = DataGridViewTriState.True;
            this.dataGridViewFilterTextBoxColumn6.DataPropertyName = "acceptFIO";
            this.dataGridViewFilterTextBoxColumn6.HeaderText = "Допускающий";
            this.dataGridViewFilterTextBoxColumn6.Name = "dataGridViewFilterTextBoxColumn6";
            this.dataGridViewFilterTextBoxColumn6.ReadOnly = true;
            this.dataGridViewFilterTextBoxColumn6.Resizable = DataGridViewTriState.True;
            this.dataGridViewFilterTextBoxColumn7.DataPropertyName = "makerFio";
            this.dataGridViewFilterTextBoxColumn7.HeaderText = "Производитель";
            this.dataGridViewFilterTextBoxColumn7.Name = "dataGridViewFilterTextBoxColumn7";
            this.dataGridViewFilterTextBoxColumn7.ReadOnly = true;
            this.dataGridViewFilterTextBoxColumn7.Resizable = DataGridViewTriState.True;
            this.dataGridViewFilterTextBoxColumn8.DataPropertyName = "Evnt";
            this.dataGridViewFilterTextBoxColumn8.HeaderText = "Состояние работ";
            this.dataGridViewFilterTextBoxColumn8.Name = "dataGridViewFilterTextBoxColumn8";
            this.dataGridViewFilterTextBoxColumn8.ReadOnly = true;
            this.dataGridViewFilterTextBoxColumn8.Resizable = DataGridViewTriState.True;
            this.dataGridViewTextBoxColumn25.DataPropertyName = "EvntDate";
            this.dataGridViewTextBoxColumn25.HeaderText = "Дата";
            this.dataGridViewTextBoxColumn25.Name = "dataGridViewTextBoxColumn25";
            this.dataGridViewTextBoxColumn25.ReadOnly = true;
            this.dataGridViewTextBoxColumn26.DataPropertyName = "closed";
            this.dataGridViewTextBoxColumn26.HeaderText = "closed";
            this.dataGridViewTextBoxColumn26.Name = "dataGridViewTextBoxColumn26";
            this.dataGridViewTextBoxColumn26.ReadOnly = true;
            this.dataGridViewTextBoxColumn26.Visible = false;
            this.dataGridViewFilterTextBoxColumn9.DataPropertyName = "disp";
            this.dataGridViewFilterTextBoxColumn9.HeaderText = "Диспетчер";
            this.dataGridViewFilterTextBoxColumn9.Name = "dataGridViewFilterTextBoxColumn9";
            this.dataGridViewFilterTextBoxColumn9.ReadOnly = true;
            this.dataGridViewFilterTextBoxColumn9.Resizable = DataGridViewTriState.True;
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.ClientSize = new Size(918, 588);
            base.Controls.Add(this.splitContainer1);
            base.Controls.Add(this.toolStripOrder);
            this.Icon = (Icon)resources.GetObject("$this.Icon");
            base.Name = "FormJournalOrder";
            this.Text = "Журнал нарядов";
            base.FormClosed +=new FormClosedEventHandler( this.FormJournalOrder_FormClosed);
            base.Load += new System.EventHandler(this.FormJournalOrder_Load);
            ((ISupportInitialize)this.dgvOrder).EndInit();
            ((ISupportInitialize)this.bsOrder).EndInit();
            ((ISupportInitialize)this.dataSetOrder).EndInit();
            this.toolStripOrder.ResumeLayout(false);
            this.toolStripOrder.PerformLayout();
            this.panelFilter.ResumeLayout(false);
            this.panelFilter.PerformLayout();
            this.panelDateFilter.ResumeLayout(false);
            this.panelDateFilter.PerformLayout();
            this.panelTree.ResumeLayout(false);
            this.splitContainerFilter.Panel1.ResumeLayout(false);
            this.splitContainerFilter.Panel1.PerformLayout();
            this.splitContainerFilter.Panel2.ResumeLayout(false);
            this.splitContainerFilter.Panel2.PerformLayout();
            this.splitContainerFilter.ResumeLayout(false);
            this.toolStripFilter.ResumeLayout(false);
            this.toolStripFilter.PerformLayout();
            this.tabControlOrder.ResumeLayout(false);
            this.tabPageView.ResumeLayout(false);
            this.tabPageEvents.ResumeLayout(false);
            ((ISupportInitialize)this.dgvEvents).EndInit();
            ((ISupportInitialize)this.bsOrderEvents).EndInit();
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            this.splitContainer1.ResumeLayout(false);
            base.ResumeLayout(false);
            base.PerformLayout();
        }


        private DataSet.DataSetOrder dataSetOrder;
        private DataGridViewExcelFilter dgvOrder;
        private BindingSource bsOrder;
        private ToolStrip toolStripOrder;
        private ToolStripButton toolBtnAddOrder;
        private ToolStripButton toolBtnEditOrder;
        private ToolStripButton toolBtnDelOrder;
        private ToolStripButton toolBtnReport;
        private ToolStripButton toolBtnReportExcel;
        private ToolStripSeparator toolStripSeparator1;
        private Panel panelFilter;
        private CheckBox checkBoxCloseOrder;
        private CheckBox checkBoxCurrentOrder;
        private CheckBox checkBoxRegistered;
        private CheckBox checkBoxNoRegistered;
        private Panel panelDateFilter;
        private ToolStripButton toolBtnReadOrder;
        private ToolStripSeparator toolStripSeparator2;
        private ToolStripButton toolBtnRefresh;
        private ToolStripSeparator toolStripSeparator3;
        private ToolStripButton toolBtnOrderClose;
        private TabControl tabControlOrder;
        private TabPage tabPageView;
        private TabPage tabPageEvents;
        private BindingSource bsOrderEvents;
        private DataGridViewExcelFilter dgvEvents;
        private DateTimePicker dateTimePickerEnd;
        private Label label2;
        private DateTimePicker dateTimePickerBegin;
        private Label label1;
        private TreeViewSchmObjects treeViewSchmObjects;
        private SplitContainer splitContainer1;
        private Panel panelTree;
        private ToolStrip toolStripFilter;
        private ToolStripButton toolBtnFilter;
        private ToolStripButton toolBtnFilterClear;
        private ToolStripButton toolBtnFind;
        private ToolStripTextBox toolTextBoxFind;
        private ToolStripButton toolBtnFindPrev;
        private ToolStripButton toolBtnFindNext;
        private ToolStripDropDownButton toolBtnAddOrderDivision;
        private SplitContainer splitContainerFilter;
        private CheckedListBox checkedListBoxDivision;
        private Label label3;
        private DataGridViewFilterTextBoxColumn dataGridViewFilterTextBoxColumn1;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn1;
        private DataGridViewFilterTextBoxColumn dataGridViewFilterTextBoxColumn2;
        private DataGridViewFilterTextBoxColumn dataGridViewFilterTextBoxColumn3;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn2;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn3;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn4;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn5;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn6;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn7;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn8;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn9;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn10;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn11;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn12;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn13;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn14;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn15;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn16;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn17;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn18;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn19;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn20;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn21;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn22;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn23;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn24;
        private DataGridViewFilterTextBoxColumn dataGridViewFilterTextBoxColumn4;
        private DataGridViewFilterTextBoxColumn dataGridViewFilterTextBoxColumn5;
        private DataGridViewFilterTextBoxColumn dataGridViewFilterTextBoxColumn6;
        private DataGridViewFilterTextBoxColumn dataGridViewFilterTextBoxColumn7;
        private DataGridViewFilterTextBoxColumn dataGridViewFilterTextBoxColumn8;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn25;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn26;
        private DataGridViewFilterTextBoxColumn dataGridViewFilterTextBoxColumn9;
        private DataGridViewFilterTextBoxColumn numDgvColumn;
        private DataGridViewFilterTextBoxColumn srNumDataGridViewTextBoxColumn;
        private DataGridViewFilterDateTimePickerColumn dateOutputDataGridViewTextBoxColumn;
        private DataGridViewFilterDateTimePickerColumn dateBeginDataGridViewTextBoxColumn;
        private DataGridViewFilterDateTimePickerColumn dateEndDataGridViewTextBoxColumn;
        private DataGridViewFilterCheckBoxColumn registeredDgvColumn;
        private DataGridViewTextBoxColumn outputMakerDataGridViewTextBoxColumn;
        private DataGridViewFilterTextBoxColumn instructionDataGridViewTextBoxColumn;
        private DataGridViewTextBoxColumn resolutionDataGridViewTextBoxColumn;
        private DataGridViewFilterTextBoxColumn srNameDataGridViewTextBoxColumn;
        private DataGridViewFilterTextBoxColumn headFioDataGridViewTextBoxColumn;
        private DataGridViewFilterTextBoxColumn acceptFIODataGridViewTextBoxColumn;
        private DataGridViewFilterTextBoxColumn watchFIODataGridViewTextBoxColumn;
        private DataGridViewTextBoxColumn makerFIODataGridViewTextBoxColumn;
        private DataGridViewTextBoxColumn otherInstructionDataGridViewTextBoxColumn;
        private DataGridViewFilterTextBoxColumn outputFIODataGridViewTextBoxColumn;
        private DataGridViewTextBoxColumn dateCloseDgvColumn;
        private DataGridViewFilterTextBoxColumn closeFIODataGridViewTextBoxColumn;
        private DataGridViewTextBoxColumn beginResDgvColumn;
        private DataGridViewTextBoxColumn EndResDgvColumn;
        private DataGridViewTextBoxColumn idDgvColumn;
        private DataGridViewFilterTextBoxColumn numDataGridViewTextBoxColumn;
        private DataGridViewFilterTextBoxColumn srNumDgvColumn;
        private DataGridViewFilterTextBoxColumn instructionDataGridViewTextBoxColumn1;
        private DataGridViewFilterTextBoxColumn acceptFIODataGridViewTextBoxColumn1;
        private DataGridViewFilterTextBoxColumn makerFioDataGridViewTextBoxColumn1;
        private DataGridViewFilterTextBoxColumn evntDataGridViewTextBoxColumn;
        private DataGridViewTextBoxColumn evntDateDataGridViewTextBoxColumn;
        private DataGridViewFilterTextBoxColumn dispDataGridViewTextBoxColumn;
        private DataGridViewTextBoxColumn closedDgvColumn;
        private DataGridViewTextBoxColumn idDgvColumnEvent;
        private CheckBox checkBoxWhereSub;
    }
}
